### ISSUE TITLE
WASM build script should print blake2-256 hash

### ISSUE THREAD

**Issue by shaunxw** [AcalaNetwork/Acala#1017]
The build script prints SHA256 hash, but the parachain system requires the hashing function configured in `frame_system` for upgrade authorization. In our case, it's `Blake2-256` (`blake2b` with 256 bit length). 

EDIT: made an issue in srtool repo https://gitlab.com/chevdor/srtool/-/issues/12

**Comment by xlc** [comment]
the UI now accepts a file and calculate the hash and subwasm supports blake2-256 hash as well
