### ISSUE TITLE
How to build HrmpChannel between two parachains?

### ISSUE THREAD

**Issue by jonathanxuu** [AcalaNetwork/Acala#1130]
Want to use `xToken` to transfer assets between 2 parachains, but don't know how to build HrmpChannel.
I have no idea how to construct request message.

**Comment by xlc** [comment]
Please check polkadot for the details.
https://github.com/paritytech/polkadot/blob/d5028035f19ced255369ea8364c1eb72074fa6cc/runtime/parachains/src/hrmp.rs#L414

Closing as this is not Acala specific question.
