### ISSUE TITLE
Homa Lite

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1168]
- module-home-lite
  - Types
    - struct TotalInfo
      - staking_currency_total: Balance
      - liquid_currency_total: Balance
  - Config
    - Currency: MultiCurrency
    - StakingCurrencyId: Get\<CurrencyId>
    - LiquidCurrencyId: Get\<CurrencyId>
    - PalletId: Get\<PalletId>
    - IssueOrigin: EnsureOrigin
  - Storage
    - PendingAmount: map u32, AccountId => Balance
    - TotalAmount: map u32 => Option\<TotalInfo>
    - CurrentBatchIndex: u32
    - StashAccount: Option\<RelaychainAccountId>
  - Calls
    - fn mint(origin, amount: Balance)
      - ensure signed
      - PendingAmount::insert(CurrentBatchIndex, who, amount)
      - send XCM to transfer KSM to StashAccount
    - fn issue(origin, new_total: Balance)
      - ensure IssueOrigin
      - Update total amount
      - CurrentBatchIndex += 1
    - fn claim(origin, who: AccountId, batch_index: u32)
      - ensure signed
      - calcualte exchange rate using TotalAmount
      - take PendingAmount
      - mint liquid currency
    - fn set_stash_account(origin, acc: RelaychainAccountId)
      - ensure root
      - update StashAccount

**Comment by syan095** [comment]
PR merged here:
https://github.com/AcalaNetwork/Acala/pull/1188
