### ISSUE TITLE
PANIC 

### ISSUE THREAD

**Issue by athena0416** [AcalaNetwork/Acala#1227]
====================

**Describe the bug**
karura node running bug the 

log is below

the command is "./acala --chain=karura --name "test" --pruning=archive --unsafe-rpc-external --unsafe-ws-external --rpc-cors=all --base-path=/root/data --ws-external --rpc-external  --ws-port 2342 --rpc-port 2343 --ws-max-connections=2000"

**Expected Behavior**

**Current Behavior**

restart the node and it doesn't work

**Steps to Reproduce**

1.
2.
3.
4.

**Additional context**

  - Node version:         Version: 1.2.0-84d4bff0-x86_64-linux-gnu
  - OS:                          ubuntu:18.04
  - Command line options:
  -                                 "./acala --chain=karura --name "test" --pruning=archive --unsafe-rpc-external --unsafe-ws-external --rpc-cors=all --base-path=/root/data --ws-external --rpc-external  --ws-port 2342 --rpc-port 2343 --ws-max-connections=2000"
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

Version: 1.2.0-84d4bff0-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:626:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   5: core::panicking::panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/panicking.rs:92:14
   6: core::option::expect_failed
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/option.rs:1241:5
   7: sc_client_db::Backend<Block>::try_commit_operation
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
   9: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::LockImportRun<Block,B>>::lock_import_and_run
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  21: std::thread::local::LocalKey<T>::with
  22: futures_executor::local_pool::block_on
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: tokio::runtime::context::enter
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/sys/unix/thread.rs:71:17
  31: start_thread
  32: __clone

Thread 'tokio-runtime-worker' panicked at 'existence of block with number `new_canonical` implies existence of blocks with all numbers before it; qed', /root/.cargo/git/checkouts/substrate-f4423eebfa0046a3/1b758b2/client/db/src/lib.rs:1309

**Comment by xlc** [comment]
same issue as https://github.com/paritytech/cumulus/issues/534 and https://github.com/PureStake/moonbeam/issues/541

**Comment by xlc** [comment]
should be fixed by 1.2.1
