### ISSUE TITLE
XCM execution fee management

### ISSUE THREAD

**Issue by shaunxw** [AcalaNetwork/Acala#1233]
### XCM execution fees

While receiving cross-chain transfer, the way to collect XCM execution fee depends on the kind of transferred asset:

- Karura/Acala native tokens, namely KAR/ACA: in this case use `WeightToFee` to figure out how much to charge.
- Foreign tokens which are listed in DEX:
  1. Firstly use `WeightToFee` to get the amount of native currency to charge.
  2. Use DEX convert to get required native currency.
- Foreign tokens which are not listed in DEX: we need to estimate a ratio between the foreign token and native tokens, and use it to get weight to foreign token amount.

### Chicken or the egg

Note that for charging foreign tokens via DEX, there is a *chicken or the egg* dilemma: the fee can't be converted in DEX until this foreign token listed, however it can't be listed until cross-chain transfer enabled and liquidity available. Thus for every foreign tokens to be listed in DEX:
1. Firstly we need to estimate a ratio between the foreign token and native token, and use it to charge XCM execution fees.
2. Then we could have cross-chain enabled, liquidity injected. And the foreign token TP could be listed.
3. Once the foreign token to native token trading path is available, replace the method to collect XCM execution fees as using DEX. The estimated ratio would be a back-up way then.

**Comment by zqhxuyuan** [comment]
I think `Trader` config inside `xcm_executor` can do the first case, isn't it? as second and third case about DEX, can `FixedRateOfForeignAsset` deal with? @shaunxw @zjb0807

**Comment by zqhxuyuan** [comment]
current transaction payment is used for sender to charge fee, and trader along with BuyExecution is used for receiver to execute xcm. after discuss with @xlc, the new design of fee charge will change to using a fee pool along with fix rate to not only support transaction payment, but also support xcm buy execution.
● the fix rate will be update once 20 blocks(need benchmark?)
● each token has its fee pool, this pool record the total balance of each token

the new workflow of transaction payment charge fee:
● if user has enough native token(e.x. KAR) for charge fee, then just use it's own balance. this part unchanged.
● else the user has enought foreign asset(e.x. KSM), but not enought of native token
  ○ calcutate fee by WeightToFee (x)
  ○ use fix rate to calculate the amount of foreign asset. 
      ■ e.x. the fix rate of KAR to KSM is m. then we get m*fee_amount_of_KAR amount of KSM(y)
      ■ the initial fix rate is determined by dex module or we could setup it an initial fixed value
  ○ transfer y KSM from sender to KSM fee pool
  ○ transfer x KAR from KAR fee pool to sender
  ○ charge fee with x KAR from sender

the new workflow of xcm buy execution:
● if user has enough native token(e.x. KAR) for weight_limit inside BuyExecution, then just use it's own balance. this part unchanged.
● else use the same machanism to deal with foreign asset

at some times later, the balance of KAR will decreasing, and other foreign asset will be increase. so we need to do swap
● if the balance of KAR getting to zero, or 20 blocks later
● at the same time, update fix rate of KAR and foreign asset

**Comment by zqhxuyuan** [comment]
the initial KAR pool should be offered by which way, treasury? we don't need complicated DEX/swap way.
