### ISSUE TITLE
Why do we need relay chain block number for vesting?

### ISSUE THREAD

**Issue by ayushmishra2005** [AcalaNetwork/Acala#1240]
Why do we need relay chain block number for vesting?

https://github.com/AcalaNetwork/Acala/blob/master/runtime/acala/src/lib.rs#L852

We can't we use  current blockchain number for Vesting?

**Comment by xlc** [comment]
relaychain block time is more stable than parachain. there are already multiple incidents causing parachain stalls for hours.
