### ISSUE TITLE
Use safe arithmetic in homa-lite

### ISSUE THREAD

**Issue by shaunxw** [AcalaNetwork/Acala#1321]
As addressed in [this review comment](https://github.com/AcalaNetwork/Acala/pull/1308#discussion_r685834295), `mul` should be `checked_mul_int`.

https://github.com/AcalaNetwork/Acala/blob/bf28d84fabfcb5b6e9653e90f5af9c78fdbd7447/modules/homa-lite/src/lib.rs#L184

**Comment by syan095** [comment]
@shaunxw 
https://github.com/paritytech/substrate/blob/e4a0cc407f60b6d3c735805881a07ae147c4beba/primitives/arithmetic/src/per_things.rs#L752-L762

Looks like the standard .mul already handles overflow. Do you think this is good enough?
I was not able to find an implementation for checked_mul and checked_mul_int for per_things

**Comment by shaunxw** [comment]
Hmmm, yeah the `PerThing` impl of `Mul` is safe. Closing this issue.
