### ISSUE TITLE
Make sure Kusama users can transfer assets on Karura via xcm

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1360]
This is useful for proxy crowdloan contributors to use KAR in their Kusama proxy account.
Needs some integration test to ensure this works.

- Identity how to construct XCM message on Kusama side to
  - transfer asset on Karura
  - call extrinsic via Transact
- Write integration test with xcm-simulator

**Comment by zqhxuyuan** [comment]
the proxy account has two types, normal and anonymous, and those two different types has different storage in Proxy pallet. for example:
- Alice is primary account
- Alice use Bob/Dave as normal proxy account
- Alice create anonymous proxy account Charlie1, Charlie2, as anonymous proxy account is generated by block number and some other data

Storage of Proxies on Proxy pallet will like:
```
Alice -> [Bob, Dave]
Charlie1 -> [Alice]
Charlie2 -> [Alice]
```

in xcm scene, we have to consider different account happend before.
|Kusama|Karura|
|--------|------|
|Alice|Alice'
|Bob/Dave|Bob'/Dave'
|Charlie1/Charlie2|Charlie1'/Charlie2'

here we use `address'` as the same public key/account, but different address on different chain.

And in this issue, at Kusama side, we want to transfer KAR with different account list above

first, Alice & Alice':
- Alice' got the KAR rewards, Alice & Alice' can recognize each other, it's supported naturaly

second, Bob/Bob':
