### ISSUE TITLE
Make sure mandala dev works

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1375]
Got a report it stopped producing blocks after 200 blocks.

**Comment by ferrell-code** [comment]
![dev_chain_test](https://user-images.githubusercontent.com/70108835/133477854-6896bb4b-7479-4598-b586-9accd4f2f5e7.png)

**Comment by ferrell-code** [comment]
Let it run overnight... Maybe should do it with the relay-chain finalizing blocks? But don't see any issues here

**Comment by xlc** [comment]
ok. in that case we can close it for now until someone else complaints
