### ISSUE TITLE
FATAL: Unable to initialize the API

### ISSUE THREAD

**Issue by vyorkin** [AcalaNetwork/Acala#1393]
**Describe the bug**

I'm trying to run the Acala node using `make run`.

**Expected Behavior**

When I go to the https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer
I can see the network explorer and there are no errors :)

**Current Behavior**

![image](https://user-images.githubusercontent.com/988849/132024557-73f0a874-2a74-4dd6-850c-d83f45a0f04d.png)

**Steps to Reproduce**

1. make init
2. make run
3. open the https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer in a web browser

**Additional context**

  - Node version: master branch
  - OS: NixOS
  - Browser: Firefox
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

**Comment by brettkolodny** [comment]
You need to add the types to polkadot.js. You can do this by going to `Settings` -> `Developer`. And then just copy paste the JSON from [this file](https://github.com/AcalaNetwork/acala.js/blob/master/packages/type-definitions/src/json/types.json).

**Comment by vyorkin** [comment]
Thank you @brettkolodny! It might make sense to mention this in readme and/or wiki for others like me
