### ISSUE TITLE
Something went wrong with the query and rendering of this component. Unable to find supported chain for

### ISSUE THREAD

**Issue by ZigmundKings** [AcalaNetwork/Acala#1422]
I connected to the apps.karura.network service via Polkadot{.js} extension, via the Kusama network (installed on Ledger)

I got the address in the apps.karura.network service (rwGzNmGNaTm4KruxJbk3vQGtwQJUXnUieEAPdupyzopRQ6n) and transferred KAR to it

Right now I can't do anything with my KAR:

SWAP doesn't work
Transfer doesn't work

in the Polkadot application{.js} extension throws an error all the time:

Something went wrong with the query and rendering of this component. Unable to find supported chain for 0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b

my KAR are just stuck and nothing can be done with them
![bugkarur](https://user-images.githubusercontent.com/90964127/133887573-3b521d22-77a2-4e5c-8668-8b9429ac461d.jpg)
 ?

**Comment by xlc** [comment]
Ledger is not yet supported.

**Comment by ZigmundKings** [comment]
Tell me, how can I withdraw my KAR from the network now ? there is an entry in the blockchain https://karura.subscan.io/account/rwGzNmGNaTm4KruxJbk3vQGtwQJUXnUieEAPdupyzopRQ6n

**Comment by xlc** [comment]
You need to derive the private key using https://github.com/polkadot-js/apps/pull/4529 or https://github.com/jacogr/sample-ledger-ed25519 and import the private key to Polkadot JS extension.

Closing as this is not the right place for this kind of questions.
