### ISSUE TITLE
Follow up of AcalaUncheckedExtrinsic 

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1428]
Follow up #1423 

- [x] More unit tests
- [x] Verify every single byte in the transaction is covered by signature
- [ ] https://github.com/AcalaNetwork/Acala/blob/4e1f574724871fbed3a74dfcc39dca1b0c0f78ea/primitives/src/unchecked_extrinsic.rs#L126
- [x] https://github.com/AcalaNetwork/Acala/blob/4e1f574724871fbed3a74dfcc39dca1b0c0f78ea/primitives/src/unchecked_extrinsic.rs#L215
- [x] https://github.com/AcalaNetwork/Acala/blob/b69a220ab8bef6f11a94b3040d69842ed9474775/runtime/mandala/src/lib.rs#L1903-L1904

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/Acala/blob/4e1f574724871fbed3a74dfcc39dca1b0c0f78ea/primitives/src/unchecked_extrinsic.rs#L126

The hash of `keccak_256` has been used here, so should not be needed here.

https://github.com/rust-blockchain/ethereum/blob/145923737eedb053405a8bd0a8dd72e6bc446f14/src/transaction.rs#L204

**Comment by zjb0807** [comment]
https://github.com/paritytech/substrate/pull/10835
