### ISSUE TITLE
Homa Protocol Design

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#143]
# homa

- ### module-homa

  - Type
    - enum RedeemStrategy
      - Immedately
      - Target(EraIndex)
      - WaitForUnbonding
  - Trait: module_staking_pool::Trait
  - Storage
  - Constant
  - Call
    - mint(origin, amount: StakingBalance)
      - Lock DOT and mint LDOT
    - redeem(origin, amount: LiquidBalance, strategy: RedeemStrategy)
  - Module

### module-homa-council

- Type
  - struct UnlockChunk
    - value: Balance
    - era: EraIndex
  - struct BondingLedger
    - total: Balance
      - total amount of locked LDOT
    - active: Balance
      - total amount of bonded LDOT considered for nomination
    - unlocking: Vec\<UnlockChunk>
      - unlocking chunks, ordered by unlocking block
      - i.e. new unlocking chunk always added to end, unlocked chunk removed from front
- Trait
  - type Currency: BasicLockableCurrency
  - type PolkadotAccountId
  - type Bridge: PolkadotBridgeState
- Storage
  - Nominations: map AccountId => Vec\<PolkadotAccountId>
  - Ledger: map AccountId => BondingLedger
  - Votes: map PolkadotAccountId => Balance
  - Nominees: Vec\<PolkadotAccountId>
- Constant
  - NominateesCount: Get\<u32>
  - MinBondThreshold: Get\<Balance>
- Call
  - bond(origin, amount: Balance)
    - lock LDOT
    - total bonded amount must be more than MinBondThreshold
  - unbond(origin, amount: Balance)
    - move LDOT to unlocking 
    - total bonded amount after unbond must be more than MinBondThreshold or zero
    - if all fund are unbonded, remove nomination
  - rebond(origin, amount: Balance)
  - withdraw_unbond(origin)
    - withdraw unlocked LDOT
  - nominate(origin, targets: Vec\<PolkadotAccountId>)
    - ensure_signed
    - ensure have bonded LDOT
  - chill(origin)
    - remove nominations
- Module
  - rebalance()
  - impl NomineesProvider
    - Read all Votes and find top NominateesCount
  - impl OnNewEra
    -  rebalance()

- ### module-staking-pool

  - Type
    - trait NomineesProvider
      - nominees(): Vec\<AccountId>
    - struct UnlockChunk
      - value: StakingBalance
      - era: EraIndex
      - claimed: StakingBalance
    - struct StakingLedger
      - total_bonded: StakingBalance
      - active: StakingBalance
      - unlocking: Vec\<UnlockChunk>
      - free: StakingBalance
    - trait OnCommission
      - on_commission(amount: Balance)
  - Trait
    - type StakingCurrency: BasicCurrency
    - type LiquidCurrencyId: BasicCurrency
    - type Bridge: PolkadotBridge
    - type Nominees: NomineesProvider
    - type OnCommission: OnCommission
  - Storage
    - ClaimedUnlockChunk: double_map EraIndex, AccountId => Amount
    - Ledger: StakingLedger
  - Constant
    - MaxBondRatio: Ratio
    - MinBondRatio: Ratio
    - MaxClaimFee: Rate
    - Commission: Rate
  - Call
    - claim_payout(origin, amount: StakingBalance, proof: Vec\<u8>)
      - claim a payout by submiting payout amount and a proof
      - during testnet phase, ensure_root, our bot will submit this every era
      - with real Polkadot bridge, verify proof matches to amount
      - comission is taken from amount
  - Module
    - rebalance()
      - bonded_percent = Ledger.total_bonded / (Ledger.total_bonded + Ledger.free)
      - if bonded_percent < MinBondPercent
        - bond more
      - if bonded_percent > MaxBondPercent
        - unbond some
    - bond(amount: StakingBalance)
    - unbond(amount: StakingBalance)
    - claim(amount: LiquidBalance, era: EraIndex)
    - claim_amount_percent(amount: StakingBalance, era: EraIndex) -> Ratio
      - free = Bridge::balance() - Bridge::ledger().total
      - available = Bridge::ledger().unlocking.map(|x| x.era <= era).sum()
      - amount / (free + available)
    - claim_period_percent(era: EraIndex) -> Ratio
      - (era - Bridge::current_era()) / BondingDuration
    - claim_fee(amount: StakingBalance, era: EraIndex)
      - TODO
    - impl OnNewEra
      - on_new_era
        - rebalance()
        - Bridge::nominate()

- ### module-polkadot-bridge

  - Type
    - trait PolkadotBridgeType
      - type BondingDuration: Get\<EraIndex>
      - type EraLength: Get\<BlockNumber>
      - type PolkadotAccountId
    - trait PolkadotBridgeCall: PolkadotBridgeType
      - bond_extra(amount: Balance)
      - unbond(amount: Balance)
      - rebond(amount: Balance)
      - withdraw_unbonded()
      - nominate(targets: Vec\<PolkadotAccountId>)
      - transfer(to: PolkadotAccountId, amount: Balance)
      - payout_nominator()
    - trait PolkadotBridgeState
      - ledger(): StakingLedger
      - balance(): Balance
      - current_era(): EraIndex
    - trait PolkadotBridge: PolkadotBridgeCall + PolkadotBridgeState
    - trait OnNewEra
      - on_new_era(era: EraIndex)
  - Trait
    - type DotCurrency: BasicCurrency
    - type OnNewEra: OnNewEra
    - type MockRewardPercent: Get\<Permill>
    - type BondingDuration: Get\<EraIndex>
    - type EraLength: Get\<BlockNumber>
  - Constants
    - MockRewardPercent: Permill
    - BondingDuration: EraIndex
    - EraLength: BlockNumber
  - Storage
    - Bonded: Balance
    - Available: Balance
    - Unbonding: Vec<(Balance, BlockNumber)>
    - CurrentEra: EraIndex
    - ForcedEra: Option\<BlockNumber>
  - Call
    - simulate_slash(origin, amount: Balance)
      - ensure_root
      - Bonded -= amount
      - for testing only
    - simualte_receive(origin, to: AccountId, balance: Amount)
      - ensure_root
      - DotCurrency::deposit(to, balance)
    - simulate_redeem(origin, to: PolkadotAccountId, balance: Amount)
      - ensure_signed
      - DotCurrency::withdraw(origin, balance)
    - force_era(origin, at: BlockNumber)
      - ensure_root
      - ForcedEra = at
  - Module
    - impl PolkadotBridge
    - on_finalize
      - if now % EraLength == 0 || if now === ForcedEra
        - CurrentEra++
        - OnNewEra::on_new_era(CurrenrEra)

**Comment by wangjj9219** [comment]
close by #151
