### ISSUE TITLE
GH Action to automatically generate release issue

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1447]
Needs a GH Action to generate release issue and filling in some details from release branch

e.g. https://github.com/AcalaNetwork/Acala/issues/1326

It should:

- Create GH issue
- Fill in commit for Substrate/Polkadot/Cumulus/ORML
- Build wasm and filling in related info
- Upload wasm to https://pinata.cloud

**Comment by zjb0807** [comment]
Publishing docker image will be more friendly to local development and testing
