### ISSUE TITLE
EVM: selfdestruct with remove storage count limit

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#1458]
EVM `selfdestruct` should take a max remove storage limit and use that on `weight_info` and return the actual weight depending on actual remove count. Maybe the limit should be bounded as well.
It may not be possible to clear all storage so maybe we need a new method to clear remaining storage and refund the fee maintainer.

https://github.com/AcalaNetwork/Acala/blob/4ba09696394648909e3daacdddf027c7dc335a31/modules/evm/src/lib.rs#L883

**Comment by xlc** [comment]
Duplicates to https://github.com/AcalaNetwork/Acala/issues/612
