### ISSUE TITLE
EVM: Avoid reset storage on create contract

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#1459]
We need to think a solution to not reset storage when creating new contract. This is not bounded and the maintainer shouldn't pay for someone's else garbage. Maybe we need to make it impossible to recreate the same address

https://github.com/AcalaNetwork/Acala/blob/4ba09696394648909e3daacdddf027c7dc335a31/modules/evm/src/runner/stack.rs#L583-L584

**Comment by xlc** [comment]
we should just remove all the account storage when contract is removed

**Comment by zjb0807** [comment]
Closed by #1583
