### ISSUE TITLE
Disable skip signature check during block authoring

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#149]
https://github.com/paritytech/substrate/issues/5112#issuecomment-595677863

**Comment by burdges** [comment]
I added some `*_doublecheck` convenience methods to schnorrkel, so if you're worried then I can publish 0.9.1 with them so you can start using them, but that seems quite unlikely.

**Comment by xlc** [comment]
@burdges Thanks. We are not too worried as we are still in testnet phase anyway and can hard spoon the network in worst case scenarios.
