### ISSUE TITLE
Homa lite charge redeem fee twice upon updating redeem requests 

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1531]
https://github.com/AcalaNetwork/Acala/blob/28304b9cabe083cbf6434c5c9f0e4f30e9e10858/modules/homa-lite/src/lib.rs#L430-L432

This executed on the new redeem amount, it should only burn fee on increased amount.

**Comment by syan095** [comment]
This is now fixed
https://github.com/AcalaNetwork/Acala/blob/afcf8d29b94c607bd0c66715d2495950029a4136/modules/homa-lite/src/lib.rs#L511-L516
