### ISSUE TITLE
Local chain running into error. No more new blocks produced. 

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/Acala#154]
Environment: iMac 2017

1. Setup an Acala chain to run with the honzon platform locally.
2. At first, the chain produced blocks correctly. As shown below
![Xnip2020-03-10_23-37-51](https://user-images.githubusercontent.com/46279370/76330047-4c68ce00-6328-11ea-86b8-f235f9fe2b36.jpg)
3. `Ctrl+C` to terminate. And then use `make run` to start again.
4. The chain stopped producing blocks, giving babe error warning...
![Xnip2020-03-10_23-34-16](https://user-images.githubusercontent.com/46279370/76330229-8df97900-6328-11ea-9630-a998e3cc61e3.jpg)
 
Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by xz-cn** [comment]
PS. In the explorer, no more new blocks generated. 
![Xnip2020-03-10_23-49-43](https://user-images.githubusercontent.com/46279370/76331324-f39a3500-6329-11ea-82be-6a26ffa86b6f.jpg)

**Comment by xlc** [comment]
This is expected. This is caused by limitation of BABE that there must be at least one block per epoch. See https://github.com/paritytech/substrate/issues/4464 for more details.

You can just `make restart` to purge the chain and restart it.
