### ISSUE TITLE
Remove light client related code

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1567]
https://github.com/paritytech/polkadot/pull/4105

**Comment by zqhxuyuan** [comment]
Do we have light-node related code? the only one I found on node/service is:
https://github.com/AcalaNetwork/Acala/blob/master/node/service/src/lib.rs#L352
```
	if matches!(parachain_config.role, Role::Light) {
		return Err("Light client not supported!".into());
	}
```

**Comment by xlc** [comment]
Oh looks like we never implemented it.
