### ISSUE TITLE
Rounding error in Exchange rate calculation for Homa Lite

### ISSUE THREAD

**Issue by syan095** [AcalaNetwork/Acala#1572]
**Describe the bug**
During exchange rate calculation, there's often rounding error

**Expected Behavior**
the exchange rate should be as precise as possible

**Current Behavior**
often get 1 off rounding error

**Comment by xlc** [comment]
One example: https://karura.subscan.io/extrinsic/0x583f7370ce84b7dfe38d5bf31a63d8764f3e28e0ba3722a02a27adf4266da406

The redeem amount and mint amount of KSM mismatched by 1 unit
