### ISSUE TITLE
module-asset-registry

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1574]
Allow to support foreign asset without runtime upgrade

- Types
  - enum CurrencyId
    - Token(TokenSymbol)
    - DexShare(DexShare, DexShare)
      - Token(TokenSymbol)
      - Erc20(EvmAddress)
      - LiquidCroadloan(Lease)
      - ForeignAsset(ForeignAssetId)
    - Erc20(EvmAddress)
    - StableAssetPoolToken(PoolId)
    - LiquidCroadloan(Lease)
    - ForeignAsset(ForeignAssetId)
  - type ForeignAssetId = u16
- module-asset-registry
  - types
    - struct AssetMetadata
      - name: Vec\<u8>
      - symbol: Vec\<u8>
      - decimals: u8
      - minimal_balance: Balance
  - config
    - type RegisterOrigin: EnsureOrigin
      - root or half council
  - storages
    - AssetMetadatas: map MultiLocation => metadata
  - calls
    - fn register_foreign_asset(origin, loc: VersionedMultiLocation, metadata: AssetMetadata)
      - ensure RegisterOrigin
    - fn update_foreign_asset(origin, loc: VersionedMultiLocation, metadata: AssetMetadata)
      - ensure RegisterOrigin

    
Needs to be merged with evm-manager

**Comment by zqhxuyuan** [comment]
does this feature something like https://github.com/open-web3-stack/orml-token-registry/issues/1 ?

**Comment by xlc** [comment]
They are mostly unrelated. Token registry is a way for everyone to register & share token information. This is about a pallet that allow governance to specify token information via proposals.
