### ISSUE TITLE
sudo currencies has no effect for local chain

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/Acala#160]
All the three functions (transfer, transferNativeCurrency, updateBalance)  in sudo -> currencies are not working for a local chain. The submit was successful as shown below, but no balance change in Honzon app.

![image](https://user-images.githubusercontent.com/46279370/76433455-5275b200-63ef-11ea-9648-21eda3e51104.png)

The sudo -> airDrop function works as intended...

Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by wangjj9219** [comment]
Call `transfer` and `transferNativeCurrency ` are not sudo call,  should call in this entry:  extrinsics -> currencies.

Call `updateBalance` is sudo call,  so the entry sudo -> currencies is correct. You didn't see your operation take effect，maybe that the amount you put is too small to be swept as a dust account.
 When set balance of native token(ACA) for account which there's no ACA in it, the amount must be greater than the `ExistentialDeposit` - 10**15 (i.e. 0.001 ACA)

**Comment by xz-cn** [comment]
> `transfer` and `transferNativeCurrency ` are not sudo call, should call them by this entry: extrinsics -> currencies.
> 
> `updateBalance` is sudo call, so the entry sudo -> currencies is correct. You didn't see your operation take effect，maybe that the amount you put is too small to be swept as a dust account.
> When set balance of native token(ACA) for account which there's no ACA in it before, the amount must be greater than the `ExistentialDeposit` - 10**15 (i.e. 0.001 ACA)

I have just verified the `updateBalance` function. Indeed, it was like you said. The problem I had was because I typed in a number which was too small. It seems in the `amount` field 1e18 is actually 1.  

Now there is another issue. I have tried to update the aUSD balance of an account for three times. But the amount was accumulated. So `updateBalance` using 1, 10, 100 get me 111, instead of 100. I thought by `updateBalance` you want to erase the old value and give it a new one? Or the design goal was actually to increase instead of update?

**Comment by wangjj9219** [comment]
We design it to increase/decrease balance, you can put negative number to decrease your balance. There's no interface to directly set the account balance yet.

**Comment by xz-cn** [comment]
> We design it to increase/decrease balance, you can put negative number to decrease your balance. There's no interface to directly set the account balance yet.

I see. Thank you!
