### ISSUE TITLE
Fix test coverage after a new version of rust-bindgen is released

### ISSUE THREAD

**Issue by syan095** [AcalaNetwork/Acala#1604]
Currently the test-coverage is broken.
This is due to incompatibility between `bitvec 0.19.5` and cargo-tarpaulin. While most packages depend on bitvec "0.20.*", which is compatible therefore desired, the following dependency poses a problem
bitvec 0.19.5 <- nom 6.1.2 <- cexpr 0.5.0 <- bindgen 0.59.1.

The latest bindgen have updated the dependency of cexpr to 0.6.0, which is what we want but it is not yet "published"
https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md#changed

WIP is done on a working branch here:
https://github.com/AcalaNetwork/Acala/tree/fix/test-coverage

After bindgen has published the new version, we can come back to this and try to fix the coverage again.

**Comment by zjb0807** [comment]
Maybe you can try this:
https://github.com/AcalaNetwork/Acala/blob/faf1949a06f8266922ccf63e058903322867d22a/Cargo.toml#L118-L119

**Comment by syan095** [comment]
I gave this a try but can't get it to work. I think because we don't use this directly, but via a chain of dependencies, so the patch doesn't really get used

`
[[patch.unused]]
name = "bindgen"
version = "0.59.1"
source = "git+https://github.com/rust-lang/rust-bindgen?rev=2aed6b0216805e27228ed39988ffe1a1ffd7e940#2aed6b0216805e27228ed39988ffe1a1ffd7e940"
`

**Comment by zjb0807** [comment]
It works for me. But the `tarpaulin` works without any changes on my local computer. 
I am not sure if there is a problem with the environment or machine performance or dependenies.
```
[patch.crates-io]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev="2aed6b0216805e27228ed39988ffe1a1ffd7e940" }
```

**Comment by syan095** [comment]
nice! yeah that worked on my machine too. 
i had the wrong `[patch.crates-io]`
I'll commit the changes and see if it works
