### ISSUE TITLE
The user cannot payback the full debt for closing the vault

### ISSUE THREAD

**Issue by GuiGou12358** [AcalaNetwork/Acala#1605]
**Describe the bug**
The user cannot payback the full debt for closing the vault

**Expected Behavior**
When the user clicks on the buttons "Max" and "Confirm", the full debt is paid and the user can close the vault

**Current Behavior**

The error message is displayed:
Your vault is below the minimum required 20 kUSD, you must pay back all outstanding kUSD

I guess there is some remaining "miette" to payback but it is very hard to found the exact amount to redeem.

**Comment by GuiGou12358** [comment]
![Capture1](https://user-images.githubusercontent.com/92046056/141273436-4a8b5061-a47e-4cd4-8f6f-8454be89b51d.PNG)
![Capture2](https://user-images.githubusercontent.com/92046056/141273448-575d879f-8db6-4604-8ae8-202a9e3e0ab6.PNG)
![Capture3](https://user-images.githubusercontent.com/92046056/141273458-d47ae4be-a183-4b9a-9913-9a9ff4e6b65e.PNG)

**Comment by qwer951123** [comment]
we update the UI to auto-match the small gap. click the max button, and never worry about this again.

**Comment by GuiGou12358** [comment]
Thanks, it works now!
