### ISSUE TITLE
Parachain RPC hangs forever (but only sometimes)

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/Acala#1616]
**Describe the bug**
Parachain RPC sometimes hangs forever

**Expected Behavior**
Return data

**Current Behavior**
Sometimes hangs forever

**Steps to Reproduce**
Run a node, call RPC methods on para RPC

The embedded relay client works fine, but the karura parachain RPC sometimes hangs forever...
30511 is relay RPC, 30510 is para RPC
```
root@Ubuntu-2004-focal-64-minimal ~/toolkit # curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30511
{"jsonrpc":"2.0","result":{"currentBlock":8897249,"highestBlock":10134874,"startingBlock":61772},"id":1}
root@Ubuntu-2004-focal-64-minimal ~/toolkit # curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30510
[hangs forever]
```

**Additional context**

  - Node version: 1.6.0 Karura
  - OS: Ubuntu 20.04
  - Command line options: /usr/local/sbin/karura --port 30500 --rpc-port 30510 --ws-port 30520 --prometheus-port 30530 --execution wasm --wasm-execution compiled --chain karura --name TEST -- --port 30501 --rpc-port 30511 --ws-port 30521 --prometheus-port 30531 --name=TEST (Embedded Relay)

**Comment by xlc** [comment]
Is the node still syncing? What's the CPU usage?

**Comment by mcf-rocks** [comment]
It is still synching, cpu usage is low.On 17 Nov 2021 21:25, Xiliang Chen ***@***.***> wrote:
Is the node still syncing? What's the CPU usage?

**Comment by xlc** [comment]
This is expected when node is still syncing.

**Comment by mcf-rocks** [comment]
The kusama part is now fully synced
```
# curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30511
{"jsonrpc":"2.0","result":{"currentBlock":10151339,"highestBlock":10151339,"startingBlock":61772},"id":1}
```
But the karura RPC now gives strange results. The following is me doing the same RPC call three times about one second apart, you can see the highest block jumping around.
```
root@KARURA ~ # curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30510
{"jsonrpc":"2.0","result":{"currentBlock":959308,"highestBlock":**961692**,"startingBlock":54784},"id":1}
root@KARURA ~ # curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30510
{"jsonrpc":"2.0","result":{"currentBlock":959308,"highestBlock":**959305**,"startingBlock":54784},"id":1}
root@KARURA ~ # curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30510
{"jsonrpc":"2.0","result":{"currentBlock":959308,"highestBlock":**961518**,"startingBlock":54784},"id":1}
```

**Comment by xlc** [comment]
You node is still syncing.

**Comment by mcf-rocks** [comment]
How do you know?

If syncState don't work properly, then how can I know it is syncing and how far along is it?

According to syncState I am synced.

```# curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState"}' http://localhost:30510
{"jsonrpc":"2.0","result":{"currentBlock":959308,"highestBlock":959305,"startingBlock":54784},"id":1}```

**Comment by mcf-rocks** [comment]
I restarted the service, and it instantly caught up and it is now keeping up with the tip of the chain .... there's a bug here somewhere.

**Comment by xlc** [comment]
Use system_health to check if it is syncing.

I am going to close because:
- It is known issue that some RPC call are unreliable during syncing. We can't fix it, and I don't believe Parity is going to fix it any time soon.
- There maybe some syncing related bug, but it will be a Substrate bug that we cannot fix ourself.
- This issue is rather minor to the extend that I won't want to spend any resource ourself to diagnostic this.
