### ISSUE TITLE
ForeignAsset needs to implement xcm_executor::Config::Trader

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#1621]
https://github.com/AcalaNetwork/Acala/blob/19709245d3353c094820389c57f45c6d4ed94b0b/runtime/karura/src/lib.rs#L1502-L1509

**Comment by xlc** [comment]
I think we will do something similar to statemine.

https://github.com/paritytech/substrate/blob/3d4f1866ebb3cc73cceb12548b15775cedd3e475/frame/assets/src/types.rs#L200-L235

Use min balance ratio to determine how much we charge for fee.
