### ISSUE TITLE
Replace `parameter_types!` with `ConstU32` in runtime

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/Acala#1651]
Not a priority, but a bit cleaner

same as https://github.com/paritytech/substrate/issues/10383

**Comment by syan095** [comment]
I think this will need 
https://github.com/paritytech/substrate/commit/8a3434bb5e8f204107644cd32f97f5ba76d8714f

This can be done once substrate merge that commit into the release branch.

**Comment by syan095** [comment]
This is now complete with #2026
