### ISSUE TITLE
Node attempts to connect to unroutable IPs

### ISSUE THREAD

**Issue by leoluk** [AcalaNetwork/Acala#1655]
**Describe the bug**

Acala attempts to connect to unroutable (bogon) IPs in the peer-to-peer network by default:

```
Tue Nov 30 16:06:21 2021 TCP    <snip> 49854 =>        10.0.0.2 30344
Tue Nov 30 16:06:23 2021 TCP    <snip> 49854 =>        10.0.0.2 30344
Tue Nov 30 16:06:27 2021 TCP    <snip> 49854 =>        10.0.0.2 30344
Tue Nov 30 16:06:36 2021 TCP    <snip> 49854 =>        10.0.0.2 30344
Tue Nov 30 16:06:41 2021 TCP    <snip> 48144 =>       10.0.1.30 30344
```

This is exacerbated by a very high max peers default, leading to a large number of outbound SYN packets to unroutable/unreachable IPs.

Many hosting providers and intrusion detection systems will - quite understandably - detect and block such behavior as port scans, leading to operational issues.

Related issues, but there does not appear to be a `--no-private-ipv4` option for acala:

- https://github.com/paritytech/polkadot/issues/543
- https://github.com/paritytech/substrate/issues/9922

**Expected Behavior**

Ignore peers with bogon IPs by default.

**Current Behavior**

Tries really hard to connect to bogon IPs.

**Steps to Reproduce**

1. Run a karura or mandala node.
2. Observe outbound traffic to bogon ranges.
3. Get whacked by ISP.

**Additional context**

  - Node version: 1.6.0
  - OS: RHEL 8
  - Command line options: 
 ```
acala \
    --chain {{ acala_genesis_path }} \
    --port {{ acala_port }} \
    --ws-port {{ acala_ws_port }} \
    --rpc-port {{ acala_rpc_port }} \
    --base-path={{ acala_basedir }} \
    --pruning={{ acala_pruning }} \
    --ws-external \
    --rpc-external \
    --prometheus-external \
    --ws-max-connections {{ acala_ws_max_conns }} \
    --unsafe-ws-external \
    --unsafe-rpc-external \
    --rpc-cors=all \
    --rpc-methods={{ acala_rpc_methods }} \
    --execution=wasm
```

**Comment by xlc** [comment]
`--no-private-ipv4` is a valid CLI. Is it not working?

**Comment by leoluk** [comment]
Ah, you're right - I was looking for `--allow-ips`, `--no-private-ipv4` is there!

I guess we'll need https://github.com/paritytech/substrate/pull/9943 backported to the substrate version Karura uses, though? It doesn't have the is_global change, which is needed to catch all the relevant bogons:

https://github.com/paritytech/substrate/blob/57346f6b24875f8935280dba51fa8ab0a9ba1e39/client/network/src/discovery.rs#L517-L519

**Comment by xlc** [comment]
It should be included when we bump Substrate version. The PR is https://github.com/AcalaNetwork/Acala/pull/1628

Yeah I think we can make it default if the chain is Karura or Acala.

**Comment by xlc** [comment]
It is enabled by default for Live networks (Acala/Karuar/Mandala) https://github.com/paritytech/substrate/blob/ee8ac3a6c9c9292911afbf5ec16fbb2bb0d44b27/client/cli/src/params/network_params.rs#L72-L77
