### ISSUE TITLE
EVM playgroud not connecting to local node

### ISSUE THREAD

**Issue by petscheit** [AcalaNetwork/Acala#1667]
Hi,
I want to connect EVM playground to a local node, but am not able to. I'm running a fresh build of the node, and start it with `make run`. I wait until everything has started properly, and also see an incoming TCP connection in the node logs. The playground UI is stuck on the initialized connection load screen though. In the console this error is thrown:
```
polkadotjs.48d0477d.js:1 2021-12-03 12:05:49        
REGISTRY: Error: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at i (polkadotjs.48d0477d.js:1)
    at j (polkadotjs.48d0477d.js:1)
    at P (polkadotjs.48d0477d.js:1)
    at polkadotjs.48d0477d.js:1
    at new I (polkadotjs.48d0477d.js:1)
    at new <anonymous> (polkadotjs.48d0477d.js:1)
    at new r (polkadotjs.48d0477d.js:1)
    at n (polkadotjs.48d0477d.js:1)
    at g (polkadotjs.48d0477d.js:1)
    at new j (polkadotjs.48d0477d.js:1)
```
Am I doing something wrong or is this currently broken? The testnet also doesn't seem to work, faucet bot has been deactivated for 6 weeks now. Would be great if someone could give me some pointers.

**Comment by xlc** [comment]
We are refactoring & updating evm playground. The deployed version is too old and not compatible. There should be a new version published in few weeks time.

**Comment by adradr** [comment]
Hello, 

I am experiencing a different issue with the latest v2.1.1 node when connecting to Acala EVM Playground. Is it still under development? 
Error log on node:
```
2021-12-29 09:54:20 Accepted a new tcp connection from xx.xx.xx.xx:49467.
2021-12-29 09:54:20 WS Error <Http(Token)>: Invalid byte where token is required.   
```
Running node with the following docker command:
```
docker run -d --restart=always --name acala_node -p 30333:30333 -p 9933:9933 -p 9944:9944 -v /data-path:/acala/data acala/acala-node:latest --chain mandala --base-path=/acala/data/01-001 --ws-port 9944 --rpc-port 9933 --port 30333 --ws-external --rpc-external --ws-max-connections 1000 --rpc-cors=all --unsafe-ws-external --unsafe-rpc-external --pruning=archive --name "xxx"
```
I wasnt able to find anything related to an authentication token in terms of substrate nodes. Am I missing something or its still a compatibility issue with the Playground?

Thanks,
adr

**Comment by xlc** [comment]
The new version is not yet live.
