### ISSUE TITLE
Dusting Accounts with mapped Evm Address 

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/Acala#1668]
https://github.com/AcalaNetwork/Acala/blob/b2054d585665478422e9d14c0c8620dc832f708d/modules/evm-accounts/src/lib.rs#L310

Currently the weights are 2 writes underweight for when an account has a claimed an evm address and gets reaped... we could change the logic or update the benchmarks

**Comment by Lawrence-Acala** [comment]
Hi @ferrell-code is it still required? I'm trying to pick up what is these aged issues, can you please elaborate a bit?

**Comment by ferrell-code** [comment]
Yeah there are benchmarks where the worst case scenario is an account is killed. But those benchmarks don't account for the account being killed having an evm mapping that will be removed too. This means that a few of our benchmarks are slightly undercharging the worst case scenario... It is a minor issue but still valid

**Comment by xlc** [comment]
This won't be a blocking issue for the EVM deployment.
