### ISSUE TITLE
calc next network contract fails

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#1677]
Address generated here
https://github.com/AcalaNetwork/Acala/blob/f5afbf442a8d7607337168fb6a34bf0244b954e2/modules/evm/src/lib.rs#L690
will change when it calls `handle_mirrored_token` returning `PREDEPLOY_ADDRESS_START` and causing `CreateCollision`

This condition is true because byte at index `9` element is `1`
https://github.com/AcalaNetwork/Acala/blob/f5afbf442a8d7607337168fb6a34bf0244b954e2/primitives/src/evm.rs#L151

**Comment by zjb0807** [comment]
The NFT precompile doesn't implement. It can't be called here.
