### ISSUE TITLE
change integration-test dev dependency `xcm-emulator` to polkadot `xcm-simulator`

### ISSUE THREAD

**Issue by zqhxuyuan** [AcalaNetwork/Acala#1684]
runtime integration-test dev dependency currently `xcm-emulator`, and it's only support v0.9.11, we could change to polkadot `xcm-simulator`. and as a result, maybe we don't need `patch` in Cargo.toml?

**Comment by shaunxw** [comment]
`xcm-emulator` and `xcm-simulator` serves different purpose, we should update `xcm-emulator`, instead of replacing it.
