### ISSUE TITLE
Display 'Memory Map error' and "Disconnected" and then retart

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/Acala#169]
1. I followed your official instrution and ran the command for full node:
docker run -d --restart=always -p 30333:30333 -p 9933:9933 -p 9944:9944 -v node-data:/acala/data acala/acala-node:latest --chain mandala --base-path=/acala/data/01-001 --ws-port 9944 --rpc-port 9933 --port 30333 --ws-external --rpc-external --ws-max-connections 1000 --rpc-cors=all --unsafe-ws-external --unsafe-rpc-external --pruning=archive --name "Name of Telemetry"

But my node was often offline and restart, the log file:
![rt](https://user-images.githubusercontent.com/17925290/77418911-88a92d80-6e02-11ea-8b3b-a1cd99a1094a.jpg)

You can check the line 67201 and 67206.
And you can  my node named "5HiYHwLSQm" on [https://telemetry.polkadot.io/#/Acala%20Mandala%20TC2](url)

The item "Node Uptime" often changes but my docker image show the up status is "2 days ago":
![rt2](https://user-images.githubusercontent.com/17925290/77419512-809dbd80-6e03-11ea-8b82-5e77af64c3dc.jpg)

This situation will affect my nodes to stay online.

5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

**Comment by xlc** [comment]
This is due to out of memory. How much memory do you have?

**Comment by mar348** [comment]
4G
![mm1](https://user-images.githubusercontent.com/17925290/77530120-d473d980-6ecb-11ea-85b0-9517443b253c.jpg)
![mm2](https://user-images.githubusercontent.com/17925290/77530141-db9ae780-6ecb-11ea-9815-6fa6d0203ba6.jpg)

**Comment by mar348** [comment]
@xlc  How can i run it?

**Comment by xlc** [comment]
There are few memory leak issues in the version of Substrate we are using and they have been fixed in later version.

We won't be updating Substrate version for Mandala TC2 due to breaking changes so will just have to close this one.

Docker should restart your nodes when it is out of memory so it shouldn't affect anything other than few minutes of down time once a while.
