### ISSUE TITLE
Mandala node panics in debug mode

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/Acala#1717]
When running `make run` mandala panics on a `debug_assert!` after 2 balance transfers. 

>Thread 'tokio-runtime-worker' panicked at 'assertion failed: _success.is_ok()', /home/charlesferrell/polkadot_dev/Acala/modules/collator-selection/src/lib.rs:456

**Comment by zjb0807** [comment]
Due to `author = AccountId::default()` with `--instant-sealing` and it not exists.
