### ISSUE TITLE
Integration test with Statemine

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1763]
Need some integration test to verify token transfer compatibility with Statemine.

Should asset able to transfer token from Statemine to Karura.
Karura to Statemine is not yet possible but can still have some ignored failing tests that we can enable them later once the issue is resolved.

**Comment by shaunxw** [comment]
Refer to [integration tests with Kusama](https://github.com/AcalaNetwork/Acala/blob/bb432cb749e9365365c1c4fde96156e499c797e8/runtime/integration-tests/src/relaychain/kusama_cross_chain_transfer.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L33-L76). Will need to import latest Statemine runtime like Kusama.
