### ISSUE TITLE
 code: 13, kind: PermissionDenied, message: "Permission denied"   when  I change the acala node to the 2.2

### ISSUE THREAD

**Issue by malingzhao** [AcalaNetwork/Acala#1824]
**Describe the bug**

**Expected Behavior**

**Current Behavior**

**Steps to Reproduce**

1.
2.
3.
4.

**Additional context**

  - Node version:
  - OS:
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

**Comment by xlc** [comment]
Please provide more logs.
