### ISSUE TITLE
Balance of mirror token is different in MetaMask

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#1827]
https://github.com/AcalaNetwork/bodhi.js/issues/251

https://github.com/AcalaNetwork/Acala/blob/23139c2a53773fa41daa6ad15eb32fdde69cc245/runtime/common/src/precompile/multicurrency.rs#L121

@xlc 
Should we use `reducible_balance` for the ACA token and `total_balance` for the DOT and others?

**Comment by xlc** [comment]
Yeah I think that's the best solution we can get.
