### ISSUE TITLE
which version of Karura has `xcmHandler -> sudoSendXcm`?

### ISSUE THREAD

**Issue by 0xmostima** [AcalaNetwork/Acala#1833]
I'm trying to replicate https://wiki.acala.network/build/development-guide/composable-chains/open-hrmp-channel but after starting the local testnet I do not see `xcmHandler` in sudo, only `ormlXcm`. Additionally, the fields don't match that of https://hackmd.io/naPxPYPYSXOlK0L7WohVdQ?view , including new fields like `dest: XcmVersionedMultiLocation` and not finding `Here` in `XcmV0MultiLocation`. I'm using `acala/karura-node:2.1.1` as the karura image. Is there a newer/older version I should use instead?

**Comment by 0xmostima** [comment]
seems like the UI matches that of Karura 1.5.0. Is there a new tutorial targeting the 2.x version?

**Comment by xlc** [comment]
Yeah that’s very outdated. Karura and Bifrost XCM is live so you can just use that as a reference.

**Comment by 0xmostima** [comment]
where may I find more information about how the Bifrost - Karura channel is set-up?

**Comment by 0xmostima** [comment]
I dug around and found this: https://acala.discourse.group/t/open-hrmp-cross-chain-communication-between-bifrost-and-karura-parachain/316/5 

are these parameters replicable on local testnet? e.g. if I launch two Karura parachains, will I be able to open HRMP channels between them using the same parameters from the post?

**Comment by xlc** [comment]
It should work. But you really need to understand how HRMP & XCM works, which is outside the scope of this repo.

**Comment by 0xmostima** [comment]
I'm still confused about this. I've updated to the newest version of Karura, but I still can't see xcmHandler in sudo.

**Comment by xlc** [comment]
As I said, the docs is outdated. So please don't use the wiki page as a reference.
