### ISSUE TITLE
Karura - Bifrost HRMP Channel

### ISSUE THREAD

**Issue by 0xmostima** [AcalaNetwork/Acala#1839]
I was looking at the referenda and noticed that the block containing the transaction that sets up the HRMP channel fails with a BadOrigin error.

https://karura.subscan.io/block/499387

I happen to also experience this when I'm locally running two Karura parachains and attempt to establish HRMP channel. When I tried submitting extrinsics it gave me the BadOrigin error, and when I tried with sudo.Sudid it returned `SpRuntimeDispatchError Module: { index: 56 error: 2 } `. Any guidance on this topic? Thanks!

**Comment by 0xmostima** [comment]
<img width="974" alt="Screen Shot 2022-02-02 at 5 06 18 PM" src="https://user-images.githubusercontent.com/91517378/152245390-99bd3898-e117-483c-8796-2f7035c020ae.png">
here is the encoded call

**Comment by 0xmostima** [comment]
<img width="934" alt="Screen Shot 2022-02-02 at 5 10 17 PM" src="https://user-images.githubusercontent.com/91517378/152245935-6e080dda-418e-4c28-aec4-385eb33bf213.png">
here's the call
<img width="265" alt="Screen Shot 2022-02-02 at 5 10 55 PM" src="https://user-images.githubusercontent.com/91517378/152246009-f680833f-e0d8-4e9d-8665-9f6cbdfe7533.png">
here's the error
<img width="937" alt="Screen Shot 2022-02-02 at 5 11 21 PM" src="https://user-images.githubusercontent.com/91517378/152246056-0e1bd69e-6ee7-401a-8eee-1494a290a716.png">
 block details

**Comment by 0xmostima** [comment]
<img width="263" alt="Screen Shot 2022-02-02 at 5 14 16 PM" src="https://user-images.githubusercontent.com/91517378/152246399-5e6400b3-51e4-44bc-afbb-c9f99815168e.png">
using sudo
<img width="857" alt="Screen Shot 2022-02-02 at 5 14 36 PM" src="https://user-images.githubusercontent.com/91517378/152246457-df471197-11c2-4d1a-8d0b-b0eaf07465b2.png">
gives this error. I couldn't find anywhere in Karura's documentation or Polkadot/Kusama's documentation of what `SpRuntimeDispatchError Module: { index: 56 error: 2 } ` refers to.

**Comment by 0xmostima** [comment]
My setup is here: https://github.com/0xmostima/parachain-launch/blob/master/config.yml

And I can confirm that both parachains are producing blocks

**Comment by xlc** [comment]
This is a privileged call, you can just call it.

For testnet, you can just use sudo to invoke it.

**Comment by 0xmostima** [comment]
I'm running a local chain and Alice is the sudo. But when I tried to call it with sudo, parachain returned  this `SpRuntimeDispatchError Module: { index: 56 error: 2 }` . What more information I could provide that could help figure out if I'm using sudo correctly?

**Comment by 0xmostima** [comment]
> <img alt="Screen Shot 2022-02-02 at 5 14 16 PM" width="263" src="https://user-images.githubusercontent.com/91517378/152246399-5e6400b3-51e4-44bc-afbb-c9f99815168e.png">
> 
> using sudo
> <img alt="Screen Shot 2022-02-02 at 5 14 36 PM" width="857" src="https://user-images.githubusercontent.com/91517378/152246457-df471197-11c2-4d1a-8d0b-b0eaf07465b2.png">
> 
> gives this error. I couldn't find anywhere in Karura's documentation or Polkadot/Kusama's documentation of what `SpRuntimeDispatchError Module: { index: 56 error: 2 } ` refers to.

this is the sudo call I attempted

**Comment by shaunxw** [comment]
> I'm running a local chain and Alice is the sudo. But when I tried to call it with sudo, parachain returned this `SpRuntimeDispatchError Module: { index: 56 error: 2 }` . What more information I could provide that could help figure out if I'm using sudo correctly?

You'll need to check what `Module: { index: 56 error: 2 }` is in your runtime config. `index` is the index of the pallet in `consturct_runtime`, and `error` is the index in the pallet custom `Error`.

**Comment by 0xmostima** [comment]
Thanks! I'm using parity/polkadot:v0.9.13 and acala/karura-node:2.1.1 , any pointers to where I could find `consturct_runtime`?

**Comment by xlc** [comment]
global search in the repo will find it. but here it is https://github.com/AcalaNetwork/Acala/blob/764858b8a9c72bfdc2c5969e719a2c3c13ddc6f2/runtime/karura/src/lib.rs#L1930

**Comment by 0xmostima** [comment]
seems like it is an SendFailure: https://github.com/open-web3-stack/open-runtime-module-library/blob/8d076372849a4dced5468f0f14db96b7145160ee/xcm/src/lib.rs#L65 Will try sending simpler messages for now to see if my setup is correct.

**Comment by 0xmostima** [comment]
turns out it is an InvalidOrigin error (https://github.com/paritytech/polkadot/blob/d2a156deafab68237d88c1dd8e2979915e521421/xcm/pallet-xcm/src/lib.rs#L255) when I called the same thing using polkadotXcm. Any clues into why this is the case? I'm still in sudo

**Comment by 0xmostima** [comment]
i believe that this line may have triggered the error: 
https://github.com/paritytech/polkadot/blob/d2a156deafab68237d88c1dd8e2979915e521421/xcm/pallet-xcm/src/lib.rs#L462
