### ISSUE TITLE
UnweighableMessage when transferring BNC

### ISSUE THREAD

**Issue by 0xmostima** [AcalaNetwork/Acala#1842]
<img width="886" alt="Screen Shot 2022-02-02 at 8 58 56 PM" src="https://user-images.githubusercontent.com/91517378/152268789-d4898f51-5e34-4a65-addf-1c7783922798.png">

I'm setting up a local testing system with parity/polkadot:v0.9.13 and two acala/karura-node:2.2.2 parachains. HRMP bi-directional channel is set-up using preopenHrmpChannels in the configuration file. When I'm calling xTokens.transfer, it fails with an error code translated to be UnweighableMessage . Here are my input arguments:

<img width="595" alt="Screen Shot 2022-02-02 at 9 01 53 PM" src="https://user-images.githubusercontent.com/91517378/152269058-919612d2-4003-4f34-b36d-fc5145ead26d.png">

Any clues as to when a message is "unweighable"? Thanks!

**Comment by zqhxuyuan** [comment]
first, If you try transfer cross-chain token to sibling asset, the parents should be `1` not `0`. 
second, the error code=`5`, translated to `XcmExecutionFailed`, not `UnweighableMessage`, because it's zero-based index.
