### ISSUE TITLE
BalanceTooLow when transferring BNC

### ISSUE THREAD

**Issue by 0xmostima** [AcalaNetwork/Acala#1847]
I've set up two Acala chains locally with bi-directional HRMP channels opened. I attempted to transfer BNC, but the recipient parachain keeps erroring out. Here's the message being sent:

<img width="616" alt="Screen Shot 2022-02-05 at 5 22 56 PM" src="https://user-images.githubusercontent.com/91517378/152660934-a100d915-c357-4981-9ded-1991a191813b.png">

Here's the error generated on the recipient parachain:

<img width="1188" alt="Screen Shot 2022-02-05 at 5 24 11 PM" src="https://user-images.githubusercontent.com/91517378/152660977-72624351-ffe6-49f5-9719-5194ed275dc5.png">
 
My set-up docker file is available here: https://github.com/0xmostima/parachain-launch/blob/master/config.yml
What could be the potential error?

**Comment by 0xmostima** [comment]
Additionally, I did refer to #866, but checking the balances of BNC in the recipient chain turned out to be nothing. Also, the pallet structure and API names seem to be different compared to last April.

**Comment by 0xmostima** [comment]
I also wonder if this has to do with existential deposit, so I tried varying the amount of BNC transferred all the way to 900000000000000, but with no avail.

**Comment by 0xmostima** [comment]
this may be the line that failed: https://github.com/open-web3-stack/open-runtime-module-library/blob/61e7e27923e3d9e5bfdf19438be9f30e6d653994/xcm-support/src/currency_adapter.rs#L148

**Comment by zqhxuyuan** [comment]
you should first deposit BNC token to parachain karura sovereign account on parachain bifrost, like testcase:

https://github.com/AcalaNetwork/Acala/blob/master/runtime/integration-tests/src/relaychain/kusama_cross_chain_transfer.rs#L99-L101

**Comment by 0xmostima** [comment]
is there a way to change the runtime configuration / make an extrinsic call from polkadot.js to do the deposit?

**Comment by zqhxuyuan** [comment]
you can use `tokens` module to issue extrinsic from polkadot.js that depost token to `5Eg2fntJ27qsari4FGrGhrMqKFDRnkNSR6UshkZYBGXmSuC8` account which is parachain 2000 sovereign account.

**Comment by 0xmostima** [comment]
it finally works! thank you so much!
