### ISSUE TITLE
Inconsistent v0.9.16 Substrate deps

### ISSUE THREAD

**Issue by shaunxw** [AcalaNetwork/Acala#1853]
Some Substrate deps in `Cargo.lock` are `4aeb95f7f38fcd519e2628f32f79044a8fef99d5`, but some others are `1c2332db8b6784d10bba55db794c5476aa49732a`. This is probably because new introduced deps are not included in cargo patch.

We need to check `Cargo.lock` and make sure all deps are included in patch.

**Comment by zqhxuyuan** [comment]
relates to: https://github.com/nutsfinance/stable-asset/pull/16

**Comment by shaunxw** [comment]
The same issue exists with Cumulus and Polkadot deps. Search `polkadot?branch=` and `cumulus?branch=` in `Cargo.lock`

**Comment by zqhxuyuan** [comment]
👍 should be call using `?rev`, the new introduced deps is mainly by `test-service`, I'll add it.

**Comment by shaunxw** [comment]
They should be `?rev` if covered in patches.
