### ISSUE TITLE
Enable transaction payment after DEX available on acala

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#1855]
- [ ] ensure there have enough ACA/AUSD/LCDOT/DOT [23M5ttkmR6KcoTAAE6gcmibnKFtVaTP5yxnY8HF1BmrJ2A1i](https://acala.subscan.io/account/23M5ttkmR6KcoTAAE6gcmibnKFtVaTP5yxnY8HF1BmrJ2A1i)
- [ ] ensure trading pair is enbled.
    - [ ] AUSD, ACA
    - [ ] LCDOT, AUSD, ACA
    - [ ] DOT, LCDOT, AUSD, ACA
- [x] do `enable_charge_fee_pool` for AUSD/LCDOT/DOT
    - pool_size: 5 ACA
    - threshold: 2.5 ACA
- [ ] check sub account got enough ACA token, and ED of foreign asset
    - [5EYCAe5fiQJsnu9dCLUDXThMsK8EMX98rZ5qskEa4EmEv65X](https://acala.subscan.io/account/5EYCAe5fiQJsnu9dCLUDXThMsK8EMX98rZ5qskEa4EmEv65X)
        - 5ACA = 5,000,000,000,000
        - AUSD: 100000000000
    - [5EYCAe5fiQJsnu9dCLUDb2Z6pcuhMrJDp14hP6cUahggTMDc](https://acala.subscan.io/account/5EYCAe5fiQJsnu9dCLUDb2Z6pcuhMrJDp14hP6cUahggTMDc)
        - 5ACA = 5,000,000,000,000
        - DOT: 100000000
    - [5EYCAe5fiQJsnu9dCLUDebQqmvhANBTJmT3YtSzP7Ac7zoj9](https://acala.subscan.io/account/5EYCAe5fiQJsnu9dCLUDebQqmvhANBTJmT3YtSzP7Ac7zoj9)
        - 5ACA = 5,000,000,000,000
        - LDOT: 500000000
    - [5EYCAe5fiQJsnu9dCLVKENAbkyEcFhRfGcc89jWnD7KSUiEz](https://acala.subscan.io/account/5EYCAe5fiQJsnu9dCLVKENAbkyEcFhRfGcc89jWnD7KSUiEz)
        - 5ACA = 5,000,000,000,000
        - LCDOT: 100000000

**Comment by zjb0807** [comment]
@zqhxuyuan Is there anything to add?

**Comment by zqhxuyuan** [comment]
I think we don't support using LCDOT as transaction fee payment yet. because we don't support convert LCDOT related location to LCDOT token.

https://github.com/AcalaNetwork/Acala/blob/master/modules/transaction-payment/src/lib.rs#L904

**Comment by zjb0807** [comment]
LCDOT only in the Acala network. When LCDOT/DOT trading pair enable, it can be paid for tx fee.
