### ISSUE TITLE
New Acala NFTs not rendering in apps.acala.network/portfolio/nft

### ISSUE THREAD

**Issue by sourabhniyogi** [AcalaNetwork/Acala#1858]
**Describe the bug**

A new NFT that I minted from a class that I creates does not appear in the Acala dapp the same way as the new Crowdloan contributor NFT.

**Steps to Reproduce**

1. I setup an IPFS item, expecting to use `bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu` as the metadata
  https://bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu.ipfs.dweb.link

My IPFS metadata link is
  https://bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu.ipfs.dweb.link
which is ALMOST like 
  https://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.dweb.link/acala-crowdloan-contributor.gif
but not exactly.  

2. Following the ACA crowdloan NFT reward, I created a NFT class
 https://acala.subscan.io/extrinsic/0x07e0e7f347f03c0253c30a81a3215c8f484ca2bee907c9cc6e5f791518af8731
which was assigned "3" as the class.  

The metadata for the class (3) is `bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu`

3. I then minted an NFT successfully using `proxy/proxy` => `nft/mint`:
 https://acala.subscan.io/extrinsic/0xde074894adaea02f06a534fc0d6f7a41fdce0b5b3bce668ee3455a22fd218635
which was token 0 of the class "3".

I set the metadata of the token to the same `bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu` as it appeared to be required.  

4. However, my minted NFT (token "0" of class "3") doesn't appear in the Acala "Collectibles" section
 https://apps.acala.network/portfolio/nft
as expected.

**Expected Behavior**

I expected https://bafybeidjnsvu6kbwlokdkckvpbml2icisoy7xwnmj4mqpbwbhgmgv53ksu.ipfs.dweb.link to render in https://apps.acala.network/portfolio/nft but it did not --

Is there a precise answer on what the Acala app requires for the { class, token } metadata to render for a new class/token?

Also, we expected to supply JSON objects like 
  https://docs.opensea.io/docs/metadata-standards
for the class and token metadata instead of just an IPFS hash.  What JSON metadata would work in addition to an IPFS hash as the metadata?

**Comment by wangjj9219** [comment]
The nft module is available on-chain, but the front-end hasn't supported it well. 
Currently, we also have a whitelist that only these NFTs published by officials can be displayed on the front-end, we are planning to remove this restriction. At that time, users can directly upload images on the front end to mint NFTs.

If you mint NFT by handly call, The front-end has some specification for CID, you can refer to this practice:

`Acala Crowdloan Contributor 2021` published by foundation. We use `bafybeidwelvgywzwmnvv46xdzldl2pw6gaprq7aalelu2pp372x3abth74` as `CID` when create_class, the `metadata.json` file of the NFT is stored in the IPFS directory corresponding to this `CID`. Note that the `metadata.json` file is under the directory corresponding to this `CID`, not directly connected to the `metadata.json` file by the `CID`.

Class CID: bafybeidwelvgywzwmnvv46xdzldl2pw6gaprq7aalelu2pp372x3abth74
CID directly link the folder: https://ipfs.io/ipfs/bafybeidwelvgywzwmnvv46xdzldl2pw6gaprq7aalelu2pp372x3abth74
metadata.json url: https://ipfs.io/ipfs/bafybeidwelvgywzwmnvv46xdzldl2pw6gaprq7aalelu2pp372x3abth74/metadata.json

and you can see this metadata.json:
```
```

**Comment by sourabhniyogi** [comment]
Thank you for the detailed explanation -- we can certainly follow the example.  Here are some follow up questions:
1. are Acala NFT classes and tokens expected to _always_ use IPFS hashes in the "metadata" attribute of `createClass` and `mint` instead of `metadata` field holding a JSON string?  
2. The current Acala app is showing the image from the _class_ rather than the _token_ -- if we wanted to mint a _token_ from the class and specify the `metadata` correctly, how should the metadata be specified?  Would the _token_'s `metadata` specified in the `mint` be an IPFS hash with `/metadata.json` holding the JSON object with `name`, `image` and `description` attributes?  
3. Could the `image` attribute for the _class_ or _token_ be anything other than an IPFS hash, e.g. could it be an Amazon S3 bucket?

**Comment by xlc** [comment]
We don't have a solid spec on this as yet as Acala Foundation is the only user currently. We are happy to start drafting some spec with anyone interesting on this and hopefully will have something that is suitable for most of the use cases.
