### ISSUE TITLE
Require input token and output token are different

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1875]
For DEX, the input token and final output token should be different.

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/Acala/blob/267f34e46e8c9154de92debc461ef0e4305110dc/primitives/src/lib.rs#L128-L142

It was checked here.

**Comment by xlc** [comment]
https://github.com/AcalaNetwork/Acala/blob/267f34e46e8c9154de92debc461ef0e4305110dc/modules/dex/src/lib.rs#L342

this is not checked
