### ISSUE TITLE
seems karura runtime wrongly mix with some integration test features

### ISSUE THREAD

**Issue by yrong** [AcalaNetwork/Acala#1878]
https://github.com/AcalaNetwork/Acala/blob/54db3acd409a0b787f116f20e163a3b24101ce38/runtime/integration-tests/Cargo.toml#L117

`cargo build --release --features=with-karura-runtime`

kusd transfer back from bifrost will fail, some discussion with @zqhxuyuan

**Comment by yrong** [comment]
not sure this fix will work,seems no difference. verified kusd transfer will work by just remove [this](https://github.com/AcalaNetwork/Acala/blob/9a65b96dda88568e846805f7fb19ca663c1c2b4f/Cargo.toml#L20) from build
@xlc suggest to seperate integration test completely from release, maybe add another feature just for test is better

**Comment by zqhxuyuan** [comment]
eithe we use https://github.com/AcalaNetwork/Acala/pull/1877 for now or remove runtime-integration-tests from build.
