### ISSUE TITLE
New path validation makes arbitrage less efficient 

### ISSUE THREAD

**Issue by bob5436456** [AcalaNetwork/Acala#1910]
**Describe the bug**
Before the last release swaps such as KUSD-> KSM-> LKSM->KUSD could be done when pool prices were imbalanced
For example: https://karura.subscan.io/extrinsic/0xdf45ac5aecd9175ba275ba122ab5670c92075db0704774791e22a3446698a856
Now this path is deemed invalid and bots are attempting stuff like [this](https://karura.subscan.io/extrinsic/0x17a4f26786774d197e7abc63750fdc823be6bdc624bc825b88453ae6d4290ab4) making price balancing less efficient.

I believe the issue is related to [these](https://github.com/AcalaNetwork/Acala/pull/1887) changes

**Comment by xlc** [comment]
Such operation is considered mistake for normal swap interaction and therefore disallowed.
For you use case, you can break it up to multiple tx and submit a batch call to achieve similar result.
