### ISSUE TITLE
Module Transaction Payment refactor

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1912]
The current custom fee handling requires integrate all the known support pairs to try to find a supported pair to charge tx fee. This is fine if we only have limited supported fee token but will be too slow when number of supported asset grows.

- module-transaction-payment
  - Types
  - Config
    - CustomFeeSurplus: Get\<Percent>
      - 50% for Karura & Acala
    - AlternativeFeeSurplus: Get\<Percent>
      - 25% for Karura & Acala
    - DefaultFeeTokens: Get<Vec\<CurrencyId>>
      - KSM, kUSD, LKSM for Karura, DOT, aUSD, LCDOT, LDOT for Acala
  - Calls
    - fn with_fee_path(origin, path: Vec\<CurrencyId>, call: Call)
      - dispatch call
      - no additional logic within this call
    - fn with_fee_currency(origin, currency: CurrencyId, call: Call)
      - dispatch call
      - no additional logic within this call
  - ChargeTransactionPayment
    - match call
      - with_fee_path:
      - with_fee_currency:
        - use the path / currency tx pool for fee payment
        - CustomFeeSurplus additional tx fee
      - others
        - try native token
          - no additional tx fee
        - try AlternativeFeeSwapPath
          - AlternativeFeeSurplus additional tx fee
        - try DefaultFeeTokens
          - AlternativeFeeSurplus additional tx fee

All tokens that can be converted into native token will be supported as fee token without any additional registration.
Frontend needs to be updated to detect a custom fee token is required and use `with_fee_path` or `with_fee_currency` to wrap calls.
Discounted fee when paying with native token.
Slightly discounted fee when user select a default fee path (that's not native).

**Comment by zjb0807** [comment]
If the user uses `with_fee_currency ` with `ERC20` to pay for the tx fee, how to get the swap path?

**Comment by xlc** [comment]
`with_fee_path` can be used to specify a path directly. `with_fee_currency` requires there to be a tx fee pool first

**Comment by zjb0807** [comment]
> `with_fee_path` can be used to specify a path directly. `with_fee_currency` requires there to be a tx fee pool first

https://github.com/AcalaNetwork/Acala/blob/01c72e8dadcb0af65a55750941b26760ee41ccbc/modules/transaction-payment/src/lib.rs#L616-L624

`enable_charge_fee_pool` needs to provide the path,  the same as the register path.

```
DefaultFeeTokens: Get<Vec<CurrencyId>>
KSM, kUSD, LKSM for Karura, DOT, aUSD, LCDOT, LDOT for Acala
```
This still needs a path to KAR/ACA.

**Comment by xlc** [comment]
We can update `enable_charge_fee_pool ` to take a path as well and then no need to have `set_global_fee_swap_path`

**Comment by zqhxuyuan** [comment]
> This(DefaultFeeTokens) still needs a path to KAR/ACA.

I think we already have those DefaultFeeTokens path to KAR.

https://github.com/AcalaNetwork/Acala/blob/3df0cc75b38870eacbac335a6378b7090afaaa9e/runtime/karura/src/lib.rs#L1172-L1175

**Comment by zqhxuyuan** [comment]
For Dapp, the condition of which wrappend call or unwrapped call used:
- token not exist in `GlobalFeeSwapPath` storage: use `with_fee_path(call, path)`, should provide path list which enabled by dex
- token in `GlobalFeeSwapPath` but not exist in [DefaultFeeTokens](https://github.com/AcalaNetwork/Acala/blob/72316317eed96a8bd7dde55873bc88a8945557af/runtime/karura/src/lib.rs#L1175): use `with_fee_currency(call, token)`
- token in `GlobalFeeSwapPath` and also exist in DefaultFeeTokens: unwrapped call

surplus:
- `with_fee_path` and `with_fee_currency`: query_fee_details() * 1.5
- no wrap call:
    - native: query_fee_details()
    - DefaultFeeTokens: query_fee_details() * 1.25
