### ISSUE TITLE
XCM  weight payment has strange complication which seems kind of not needed 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AcalaNetwork/Acala#1921]
As Can pay in KSM via next formula:

```python
number_of_instructions = 5
price_per_instructions = 100500
weight_per_message =  number_of_instructions * price_per_instructions 
native_to_ksm = 1/ 50
weight_per_second = 1_000_000_000_000
weight_of_remark = 125 * (weight_per_second / (1000 *1000)) 
native_unit  = 10**12
max_tx_per_second = weight_per_second / weight_of_remark

# this is weird
base_tx_in_native_unit = max_tx_per_second *  native_unit / 1000

total_weight_for_transaction  = weight_per_message /  weight_per_second

# SECONDS * (KSM / NATIVE) *(NATIVE/ SECONDS)    
# eventually this just 8x of message weigth, and transform decimals (so in default case these are 12 = 12)
required_ksm_amount = total_weight_for_transaction * native_to_ksm * base_tx_in_native_unit
```

So what I see very complicated way to multiply by 8 as I see. May be I am  wrong so.

Why not to `weight -> weigh to fee polynomial -> some base/native coin -> some static ration conversion`?

**Comment by xlc** [comment]
I don't understand your question. Can you add links to some code and your suggestion?

**Comment by zqhxuyuan** [comment]
I guess the formula relates to:

https://github.com/AcalaNetwork/Acala/blob/c1bd96ce10bd948b2dad4817ead013cc14b24cd7/runtime/karura/src/constants.rs#L83-L91

**Comment by dzmitry-lahoda** [comment]
Yes, that formula.  No performance.

basic weights depends on https://github.com/AcalaNetwork/Acala/blob/9dfa889afea18b4dbff49f3e7fef3e26064fcb91/runtime/acala/src/constants.rs#L70

so for bring your own gas payments
1. WeightToFeePolynomial - to make sure that weight is properly exchanged into ACA fee (depends on ExtrinsicBaseWeight). This is `speed` element.
2. Oracle/DEX/hardcode constant to get how ACA/KSM ratio
3. Base XCMP weight - because as I see there is no metering on top.

**Comment by xlc** [comment]
So what's the question? Are you suggesting we can simplify this or something?

**Comment by dzmitry-lahoda** [comment]
yes. question was suggestion to simplify things. i "simplfied" in composble. i hope I did not harm. so allow more clear manipulation of prices and compute resources with less parameters.

**Comment by dzmitry-lahoda** [comment]
i thin as soon as you may write math of acala coversions in that area, you may find something to simplify too

**Comment by xlc** [comment]
Yeah we just build the formula as it goes without spending much time improving it. It is not a priority anyway compare to everything else.
