### ISSUE TITLE
Place the token contract for each precompiled

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/Acala#1947]
Sudo needs to be used on Mandala to Place the token contract for each precompiled that exists.

Does this also needs to be done for other Karura & Acala testnets?

**Comment by ThunderDeliverer** [comment]
This also breaks all of our Acala EVM+ specific tutorials, so it's a pretty big pain

**Comment by zjb0807** [comment]
Metamask can't import LDOT(`0x0000000000000000000100000000000000000003`) because `Symbol must be 11 characters or fewer.`

**Comment by zjb0807** [comment]
All of the tokens are deployed on the mandala testnet. Please have a look.
https://github.com/AcalaNetwork/predeploy-contracts/blob/e968d27b04f16c432a08a4636a1edb322b39e933/contracts/utils/Address.sol#L6-L28

**Comment by zjb0807** [comment]
@gluneau 
> Sudo needs to be used on Mandala to Place the token contract for each precompiled that exists.

The token contracts are in the genesis file. If mandala is reset, manual deployment is not required.

> Does this also needs to be done for other Karura & Acala testnets?

Yes. We will selectively deploy the required contracts manually.

**Comment by gluneau** [comment]
Issue resolved.
