### ISSUE TITLE
add `MaxEncodedLen` and remove `without_storage_info`

### ISSUE THREAD

**Issue by zqhxuyuan** [AcalaNetwork/Acala#1972]
https://github.com/paritytech/substrate/pull/10810

**Comment by zqhxuyuan** [comment]
apart from: https://github.com/AcalaNetwork/Acala/pull/1984 and https://github.com/open-web3-stack/open-runtime-module-library/pull/717 there're still some module can't remove `without_storage_info` for now:
- MultiLocation related module: asset_registry & xcm_interface & unknown-tokens(orml)
- BTreeMap: orml-rewards & 
- Time: orml-oracle & dex-oracle
- Call: orml-authorities
- Task: idle-scheduler
- evm: evm & evm-bridge
- nft
- Vec<u8>: transaction-pause

**Comment by zjb0807** [comment]
Closed by #1984
