### ISSUE TITLE
Update asset registry to support all tokens

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1990]
Currently asset registry is not used for buildin tokens. To improve consistency and make things more generalized, we should allow registry token information for `CurrencyId::Token` as well.

**Comment by zqhxuyuan** [comment]
we can also issue registry asset tx for buildin tokens on migration or manual execution(?), and also add data to genesis build for convenient testing. if so, we can delete bunch of `Trader` config: 

https://github.com/AcalaNetwork/Acala/blob/5a8f381a95649eb74385fb7db31421d78118a651/runtime/karura/src/xcm_config.rs#L196-L204
