### ISSUE TITLE
remove unused param

### ISSUE THREAD

**Issue by gilescope** [AcalaNetwork/Acala#2001]
I don't think this is actually used anywhere is it?
```rust
parameter_types! {
	pub MaxDownwardMessageWeight: Weight = RuntimeBlockWeights::get().max_block / 10;
}
```

**Comment by gilescope** [comment]
label as easy first issue?

**Comment by zqhxuyuan** [comment]
yeah, it can be removed if it's not used, I think this may be belong to some old config.
