### ISSUE TITLE
Homa optimizations

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#2112]
Currently if you want to get total bounded, you've to iterate staking ledgers and calculate the total. This is expensive especially if you want to just read `current_exchange_rate` and unpredictable for EVM homa precompile to know how much gas it will cost for this operation. I suggest we either have a storage `TotalBounded: Balance` and calculate every time `do_update_ledger ` is called which will be cheaper because most items will be in `OverlayedChanges` or at least we keep track of StakingLendgers count so we know how many iterations it will make.

https://github.com/AcalaNetwork/Acala/issues/2084

**Comment by ferrell-code** [comment]
Yeah I had similar thoughts, we could alternatively store the ledgers in a `BoundedVec/BoundedBTree`
