### ISSUE TITLE
Deploy mirrored token on acala checklist

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#2166]
- [x] ACA 0x0000000000000000000100000000000000000000
- [x] AUSD 0x0000000000000000000100000000000000000001
- [x] DOT 0x0000000000000000000100000000000000000002
- [x] LDOT 0x0000000000000000000100000000000000000003
- [x] LCDOT 0x000000000000000000040000000000000000000d
- [x] TAI_DOT 0x0000000000000000000300000000000000000000
- [x] EVM 0x0000000000000000000000000000000000000800
- [x] Oracle 0x0000000000000000000000000000000000000801
- [x] DEX 0x0000000000000000000000000000000000000803
- [x] EVMAccounts 0x0000000000000000000000000000000000000806

After the wormhole bridge deployed:
- [x] register the AUSD on karura
- [ ] update karura https://github.com/AcalaNetwork/Acala/issues/1967

**Comment by zjb0807** [comment]
gasLimit: 21000000
storageLimit: 16800

**Comment by zjb0807** [comment]
gasLimit: 2,000,000
storageLimit: 16800

**Comment by zjb0807** [comment]
@xlc Please help to deploy the tokens
https://github.com/AcalaNetwork/predeploy-contracts/blob/0ac3b44dd12c6c4795af64069de28ecbb96ee9fa/resources/acala_tokens.json#L22-L93 exinclude `LCDOT_13`
```
"symbol": "RENBTC", "address": "0x0000000000000000000100000000000000000014"
"symbol": "CASH", "address": "0x0000000000000000000100000000000000000015"
"symbol": "LP_ACA_AUSD", "address": "0x0000000000000000000200000000000000000001"
"symbol": "LP_LDOT_AUSD", "address": "0x0000000000000000000200000000010000000003"
"symbol": "LP_LCDOT_AUSD", "address": "0x000000000000000000020000000001020000000d"
"symbol": "LP_LCDOT_DOT", "address": "0x000000000000000000020000000002020000000d"
"symbol": "SA_DOT", "address": "0x0000000000000000000300000000000000000000"
"symbol": "SA_3USD", "address": "0x0000000000000000000300000000000000000001"
"symbol": "FA_GLMR", "address": "0x0000000000000000000500000000000000000000"
"symbol": "FA_PARA", "address": "0x0000000000000000000500000000000000000001"
"symbol": "FA_ASTR", "address": "0x0000000000000000000500000000000000000002"
"symbol": "FA_IBTC", "address": "0x0000000000000000000500000000000000000003"
"symbol": "FA_INTR", "address": "0x0000000000000000000500000000000000000004"
"symbol": "FA_WBTC", "address": "0x0000000000000000000500000000000000000005"
"symbol": "FA_WETH", "address": "0x0000000000000000000500000000000000000006"
"symbol": "FA_EQ", "address": "0x0000000000000000000500000000000000000007"
"symbol": "FA_EQD", "address": "0x0000000000000000000500000000000000000008"
```

**Comment by xlc** [comment]
all deployed except RENBTC and CASH
