### ISSUE TITLE
Add support for predictive EVM contract addresses of  native tokens in `assetRegistry.assetMetadatas`

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/Acala#2210]
As per @ferrell-code, in this example `0x0000000000000000000500000000000000000007` the byte of 5 representing Foreign Asset and the byte of 7 well representing id 7.

This lists how evm addresses are derived for different CurrencyIds.
https://github.com/AcalaNetwork/Acala/blob/72c01a9fb3a404f92687f8c739c9594255ef8b14/primitives/src/evm.rs#L131 

I propose that the output of the metadata be augmented with the predicted EVM address as defined by the primitives above.
for example

```yaml
    [
      {
        NativeAssetId: {
          Token: AUSD
        }
      }
    ]
    {
      name: Acala Dollar
      symbol: aUSD
      evm: 0x0000000000000000000100000000000000000001
      decimals: 12
      minimalBalance: 100,000,000,000
    }
  ]
```

**Comment by xlc** [comment]
We don't want to store computed data in the onchain data. Should just have helper methods in acacia.js to do the computation.
