### ISSUE TITLE
Each tx emit `transactionPayment.TransactionFeePaid`

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#2221]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/16496415/174782972-e638bf7b-43b3-43ef-998f-f6423aa06126.png">

@zqhxuyuan

**Comment by zjb0807** [comment]
Is this expected behavior?

**Comment by zqhxuyuan** [comment]
Yes, added in https://github.com/AcalaNetwork/Acala/pull/2218.
