### ISSUE TITLE
No docker tags for 2.8.1 and 2.8.2

### ISSUE THREAD

**Issue by lsdbitrue** [AcalaNetwork/Acala#2259]
https://hub.docker.com/r/acala/karura-node/tags?page=1&name=2.8.2

**Comment by xlc** [comment]
They are runtime release. Docker image are only built for client / full release.

**Comment by lsdbitrue** [comment]
Hi, @xlc 

Should I use `ghcr.io/acalanetwork/${{ matrix.network }}-node` in production?

**Comment by xlc** [comment]
No. Just use latest docker image in docker hub.

However 2.8.0 is known to have memory leak and therefore the current recommended version is 2.6.3

**Comment by lsdbitrue** [comment]
Thanks
