### ISSUE TITLE
rs9 创建新帐户不能显示助记词

### ISSUE THREAD

**Issue by hyl1731** [AcalaNetwork/Acala#228]
系统信息：
品牌： oppo rs9
android:6.0.1
bug描述：
进入创建新帐户界面，到助记词页面不能显示助记词

波卡钱包地址：5DcffNCJrubQ5m5pZG5dbxy12aLKwgnmf6Zi4oiQUSaA8CwG
mandala:   5DcffNCJru

**Comment by wangjj9219** [comment]
here's acala network repo, plz report it to https://github.com/polkawallet-io/polkawallet-flutter/tree/develop
