### ISSUE TITLE
Make Precompile Benchmarks Overlay Aware

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/Acala#2298]
Motivation: For honzon precompile I thought it was best to have individual getters for `RiskManagmentParams` fields. seen here: https://github.com/AcalaNetwork/Acala/blob/8e92786dca81cf5d6c2c6a8cabeed923471cdd5c/modules/honzon/src/lib.rs#L430

We probably want to add getters for the rest of the fields to Honzon precompile https://github.com/AcalaNetwork/Acala/blob/8e92786dca81cf5d6c2c6a8cabeed923471cdd5c/modules/cdp-engine/src/lib.rs#L83

If a smart contract calls into 2 of the getters then they will be charged 2 reads rather than 1. Is there a way to check storage overlay so we don't double count reads. Do we care?

**Comment by ermalkaleci** [comment]
@ferrell-code no there's no way to check overlayed. Even if it was it will do extra work to check if that was is been read. Maybe a better way is to return all params as array

**Comment by ferrell-code** [comment]
Yeah that is my thoughts as well :+1:

Having getter functions seemed a bit more flexible for future changes, but seems too much of a pain
