### ISSUE TITLE
DockerHub build integration

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#23]
Setup build pipeline to build and publish docker images to DockerHub

Example: https://github.com/ETeissonniere/substrate-docker-builders

**Comment by ltfschoen** [comment]
Is this issue ready to be closed? Do the Docker Hub scripts here work https://github.com/AcalaNetwork/Acala/tree/master/scripts?

**Comment by xlc** [comment]
This meant to have CI automatically build docker images upon conditions (new tag, nightly etc) and push to docker hub.

Currently it is a manual process which should be automated at some point.
