### ISSUE TITLE
Tag inconsistency

### ISSUE THREAD

**Issue by ramilexe** [AcalaNetwork/Acala#2301]
In github latest release is 2.8.3 https://github.com/AcalaNetwork/Acala/releases/tag/2.8.3
but in Docker Hub latest version is 2.9.0 https://hub.docker.com/layers/acala-node/acala/acala-node/2.9.0/images/sha256-224e1d78878627ffb1f0721025f1a3fe158eab1e1a3ca4fb0c550b5bea97ccc9?context=explore

**Comment by ferrell-code** [comment]
We are still preparing the newest runtime release. When we finish that the github release will update to match the docker hub version

2.9.0 is a client release, to test that the new client works (so running client 2.9.0 with WASM runtime 2.8.3)

**Comment by xlc** [comment]
2.9.0 is still under internal testing phase and not yet fully released (hence no Github release).
