### ISSUE TITLE
Future rust-evm update reminder

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#2338]
when we update `rust-evm` we need to handle `invalid_code` on binary search https://github.com/paritytech/frontier/pull/840

**Comment by ermalkaleci** [comment]
https://github.com/rust-blockchain/evm/commit/51b8c2ce3104265e1fd5bb0fe5cdfd2e0938239c

**Comment by zjb0807** [comment]
Fixed in #2406
