### ISSUE TITLE
karura and acala testchain with relaychain

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/Acala#2369]
The PR https://github.com/AcalaNetwork/Acala/pull/2309 make `karura-dev` and `acala-dev` work without relaychain, it breaks the behavior of launch https://github.com/AcalaNetwork/Acala/blob/f04563748780d36d0d5d2cf157924f1ec10cf2fa/launch/config.yml#L23

Do we need a new chain flag `karura-test` and `acala-test` to revert that work with relaychain? @xlc

**Comment by xlc** [comment]
I think we can revert #2309 and add a new `karura-local` / `acala-local` that uses instant sealing.

**Comment by zjb0807** [comment]
It feels like dev work with `instant sealing` would be better.  `karura-local` / `acala-local` work with relaychain.
