### ISSUE TITLE
An problem in syncing a karura node

### ISSUE THREAD

**Issue by SixoneKui** [AcalaNetwork/Acala#2418]
**Describe the bug**

I am  syncing a karura node.  Just quite "ctrl+c" during the process and then try to resume.
See the error below.
Is there a way to save it ?

![image](https://user-images.githubusercontent.com/104364802/204116250-6c821d89-4332-48cd-b1e7-052d6a47640d.png)

**Expected Behavior**

**Current Behavior**

**Steps to Reproduce**

1.
2.
3.
4.

**Additional context**

  - Node version:
  - OS:
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

**Comment by xlc** [comment]
Did your node stop syncing or exit after this error?

**Comment by SixoneKui** [comment]
I stopped the runtime and then the server to add some storage volume. Then try to restart the syncing  and see this .

**Comment by xlc** [comment]
What happen after this? Can you share the full logs?
