### ISSUE TITLE
Consider adding rust-toolchain.toml

### ISSUE THREAD

**Issue by qezz** [AcalaNetwork/Acala#2486]
Hi guys

Would it be useful to add `rust-toolchain.toml`? It's [the toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)
This will help users and CI in figuring out the Minimum Supported Rust Version (MSRV).

Please let me know if there are any caveats with this approach

**Comment by xlc** [comment]
There isn't any reason we can't do that. It is just that we don't really need it so far and we are expecting the codebase should always works with latest nightly. That's how Substrate does it.

**Comment by qezz** [comment]
I see the point, but a certain rust version is hardcoded in the build scripts, so I got a bit confused

https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/scripts/init.sh#L7-L9

**Comment by xlc** [comment]
it is a known working version, not the required version

**Comment by ruuda** [comment]
Hi @xlc, we have automation set up that builds new versions of Acala from source when a new tag is created, and this automation started failing when Acala required a newer Rust version than it was configured to use. An automated way to discover which Rust version is needed to build a particular release would be nice, and a `rust-toolchain.toml` file is the standard way of doing this in the Rust ecosystem.

You already specify the Rust version in multiple places in the repository, e.g. in https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/scripts/Dockerfile#L4 https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/scripts/init.sh#L7 https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/.github/workflows/benchmark.yml#L78 https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/.github/workflows/coverage.yml#L43 https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/.github/workflows/test.yml#L40  https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/.github/workflows/update-tokens.yml#L23 https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/scripts/profiling/Dockerfile#L4

but this is not in a very machine-friendly format, and not in a standard location. Adding a `rust-toolchain.toml` makes it easier for tools to obtain this information, and it ensures that people who build from source use the same version that you test against. It would also make it easier for you to manage the Rust version in a single place, as Rustup will use this one by default, so you can be sure that all builds and testing use a consistent version, and you don’t forget to update a place.

> it is a known working version, not the required version

If Acala supports multiple Rust versions, are the supported versions documented anywhere? Preferably in a machine-readable location that is part of the release itself?

**Comment by xlc** [comment]
You can read it from the CI file such as [Acala/.github/workflows/test.yml](https://github.com/AcalaNetwork/Acala/blob/eda23d91fe730681b56b362323928ffa7dcb9cf0/.github/workflows/test.yml#L40). yaml file is perfectly machine readable.

**Comment by zjb0807** [comment]
Closed by #2628
