### ISSUE TITLE
Should calculate Homa DOT/LDOT rate from DEX instead of oracle price

### ISSUE THREAD

**Issue by mil99** [AcalaNetwork/Acala#256]
Current: Homa (Liquid DOT mint/redeem) DOT/LDOT exchange rate seems to be calculated from the oracle prices.

Unintended side effect: During a lack of efficient arbitrage with external markets, or when LDOT/aUSD DEX rate is out of equilibrium due to large trade
eg DEX rates 1 LDOT = 50 aUSD, 1 DOT = 300 aUSD, effective DEX DOT/LDOT rate=0.166
oracle rates 1 LDOT = 30 USD, 1 DOT = 300 USD, effective oracle DOT/LDOT rate=0.1,

a user can take advantage of swap and Homa modules to gain DOTs and LDOTs by :
1) swap LDOT to DOT at DEX rate ~0.166, then
2) deposit DOT to mint LDOT at Homa module at oracle rate 0.1,
then the user would gain ~66% of the original LDOT.

Expected behaviour: Use Homa DOT/LDOT rate from DEX rate instead eg 0.166,
then steps 1 and 2 above would not cause the unintended gain.

Make sense?

![bug3](https://user-images.githubusercontent.com/66069419/83289707-01b86d00-a218-11ea-9a1a-b3f4652fcf57.jpg)

5F3rYPmFB53XttPd8Zq9QqPxMFDUuVqDx4zjVjmqy6n4Ve4M

**Comment by wangjj9219** [comment]
The LDOT price in oracle is actually obtained from the Homa protocol, It is determined by the total issuance of L-DOT and the total DOT hold by Homa protocol.

And Dex is another trading market, the exchange rate between L-DOT and DOT is affected by how much tokens maker injected and calculated by a constant equation:  `x * y = k` same as Uniswap.

It is reasonable to use the price gap between DEX and other markets/protocal for arbitrage, the price gap will be smooth out gradually by arbitrage

**Comment by xlc** [comment]
Initially DEX price can be manipulated easily when liquidity is low so we cannot use DEX as price source.

When the liquidity is good enough, DEX can be one of the price source, which is covered by #67
