### ISSUE TITLE
Unable to broadcast a transaction with ED25519 signature type

### ISSUE THREAD

**Issue by satoshiotomakan** [AcalaNetwork/Acala#2565]
**Describe the bug**
I'm trying to broadcast a signed transaction to the Acala network. I use ed25519 elliptic curve to generate an account ID and sign the transaction.

In result, I get:
```
# Using https://github.com/polkadot-js/tools
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
```
and
```
# Using https://polkadot.js.org/apps
1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```

Signed and encoded transaction: `0x41028400e9590e4d99264a14a85e21e69537e4a64f66a875d38cb8f76b305f41fabe24a9002dd923694ec3abb8a18619bd2634ef063d3343595c1bc8f3132fcf8c9fdc3868023e8c4abc27c7036d4da347c1fdb5d70782822ad81d382e19fea76e1b2c1e01a50108000a0000c8c602ded977c56076ae38d98026fa669ca10d6a2b5a0bfc4086ae7668ed1c60070010a5d4e8`

Where accointID: `0xe9590e4d99264a14a85e21e69537e4a64f66a875d38cb8f76b305f41fabe24a9`
signature: `0x2dd923694ec3abb8a18619bd2634ef063d3343595c1bc8f3132fcf8c9fdc3868023e8c4abc27c7036d4da347c1fdb5d70782822ad81d382e19fea76e1b2c1e01`
Balance.transfer call: `0x0a0000c8c602ded977c56076ae38d98026fa669ca10d6a2b5a0bfc4086ae7668ed1c60070010a5d4e8`
signature type: `0x00`

Please note that a transaction with exactly the same parameters signed by https://polkadot.js.org/apps can be successfully broadcasted:
`0x410284007ce25fafc9eae83af94a5c08bac9262ad27a1118caccb9cb08f6f3b1d4d54371010c7d6c4df7e7dbe3e015a873db0b9a236bf320089e77da00f60b602af6063859e63043b74482fdbbcd130d37668cddb6ceb8f3814b2486b27f89a8c27a7d7687a50108000a0000c8c602ded977c56076ae38d98026fa669ca10d6a2b5a0bfc4086ae7668ed1c60070010a5d4e8`
where accountID: `0x7ce25fafc9eae83af94a5c08bac9262ad27a1118caccb9cb08f6f3b1d4d54371`
signature type: `0x01`

**Expected Behavior**

Should Acala network accept transactions signed using ED25519 elliptic curve?

**Current Behavior**

Acala network seems to reject transactions signed using ED25519 elliptic curve

**Comment by xlc** [comment]
Do you know in roughly what time / block number did you submitted the failed transaction? ED25519 transactions should be supported.

**Comment by satoshiotomakan** [comment]
@xlc thank you for the reply!
I lost the info for the transaction mentioned above.

Quick update - I added a test using [AcalaNetwork/Acala](https://github.com/AcalaNetwork/Acala/issues/2565) codebase to generate and sign a transaction.
The test looks similar to:
```rust
// corresponding address - 23hLmdxB2W7ccEGVxToQQkTbZrNng8PMXJehEi57WXJpSKV1
// corresponding account - 7ce25fafc9eae83af94a5c08bac9262ad27a1118caccb9cb08f6f3b1d4d54371
let (caller, _seed) = sp_core::sr25519::Pair::from_phrase("MNEMONIC PHRASE HERE", None).unwrap();

let function = node_runtime::RuntimeCall::Balances(pallet_balances::Call::transfer {
    dest: MultiAddress::Id(dest.into()),
    value: 1_000_000_000_000,
});

let function = function.into();
let current_block = 3888843;
let genesis_block = H256::from_str("fc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c").unwrap();
let current_block_hash = H256::from_str("a38c6a368d38c005f7dbb3efee57166d6fe52bede48331fd9e4ffc89ad1af99e").unwrap();

assert_eq!(runtime::VERSION.spec_version, 2170);
assert_eq!(runtime::VERSION.transaction_version, 2);

// ...
let signed_data: (Address, AcalaMultiSignature, SignedExtra) = (address, Signature::Sr25519(signature), extra);
let extrinsic = runtime::UncheckedExtrinsic::new(call, Some(signed_data)).unwrap();
println!("{}", to_hex(extrinsic.0.encode(), false));
```

I've successfully broadcasted the transaction generated and signed by using this test.
But I get a different account ID (therefore `Inability to pay some fees` error) if I replace `sp_core::sr25519::Pair::from_phrase` with `sp_core::ed25519::Pair::from_phrase`.

@xlc Could you please advice is it possible to get a key pair for the same account ID using ED25519 curve?

**Comment by satoshiotomakan** [comment]
@xlc thank you for the reply!
I've solved the problem, it was on my side
