### ISSUE TITLE
how to use docker to run acala/acala-node on mounted disk of Linux

### ISSUE THREAD

**Issue by SixoneKui** [AcalaNetwork/Acala#2621]
Tried to run 
docker run  -it --privileged=true acala/acala-node:2.20.0 --base-path=/mnt/HC_Volume_37317682/acala/data --chain=acala 
where /mnt/HC_Volume_37317682 is a mounted volume.

Bus this seems not working

Using df, I still see that the used of / is increasing and the used of the  mounted volume keeps unchanged.

It looks like that --base-path is not working or if I used it in a wrong way.

Thank you very much.

**Comment by zjb0807** [comment]
```
docker run -it -v /mnt/HC_Volume_37317682:/acala/data acala/acala-node:2.21.0 --base-path=/acala/data --chain=acala
```

**Comment by SixoneKui** [comment]
> ```
> docker run -it -v /mnt/HC_Volume_37317682:/acala/data acala/acala-node:2.21.0 --base-path=/acala/data --chain=acala
> ```

thank you very much.
