### ISSUE TITLE
使用Ledger的专家模式，众贷账户，质押时报错

### ISSUE THREAD

**Issue by okmind** [AcalaNetwork/Acala#2668]
**Describe the bug**
我使用subwallet，想要质押ACA，结果报错Methods not support。

![image](https://github.com/AcalaNetwork/Acala/assets/153404941/ada6a48d-7b69-469d-bfc5-c771d0b389e7)

**Expected Behavior**

**Current Behavior**

**Steps to Reproduce**

1.
2.
3.
4.

**Additional context**

  - Node version:
  - OS:
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

**Comment by okmind** [comment]
有什么方法可以把币提出来吗

**Comment by xlc** [comment]
ACA staking is not yet supported by Ledger.

**Comment by shunjizhan** [comment]
you can use ledger to stake via proxy
https://guide.acalaapps.wiki/staking/aca-staking-via-ledger
