### ISSUE TITLE
how to increase the peer account when running a node？

### ISSUE THREAD

**Issue by SixoneKui** [AcalaNetwork/Acala#2686]
how to increase the peer count as shown in https://telemetry.polkadot.io/#/0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c 
when running a node？
Are there some settings at the time of starting the node?

Many thanks

**Comment by xlc** [comment]
Use `--help` will give you all the options.
For peer count, use `--in-peers` and `--out-peers` to specify max peer count

**Comment by SixoneKui** [comment]
thanks
