### ISSUE TITLE
Remove dev mode and instant sealing mode

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#2702]
We can use Chopsticks instead to launch node from chain spec

Need to update existing tests that using dev mode

**Comment by shunjizhan** [comment]
are we going to completely remove instant-sealing mode? I think it's still useful in some scenarios, such as large scale deterministic tests (i.e. bodhi CI). These tests don't rely on mainnet status, and are faster to run on local instant-sealing mandala node

**Comment by shunjizhan** [comment]
also to test a new runtime before it's up on mainnet, we need to run a mandala instant-sealing local node

**Comment by xlc** [comment]
we can just use Chopsticks to launch a dev chain from a chain spec file. 
but we can try to update existing tests to use Chopsticks before actually remove the instant sealing mode, and then we will know if there is some use cases that cannot be replaced by Chopsticks

**Comment by shunjizhan** [comment]
sure, we can definitely try it out to see how it goes. My main concern is that light client could slow down the whole tests a little bit. But we will see, might not be an actual issue

**Comment by xlc** [comment]
there is no light client? Chopsticks is slow mostly because it need to download state from remote RPC. in this case, there are no remote RPC so it shouldn't be too slow

**Comment by shunjizhan** [comment]
oh chopsticks is not considered to be a "light client"? Maybe I was confused about the definition. But as long as it's fast without needs to fetch remote RPC, it should work well

**Comment by xlc** [comment]
light client is a client that verify consensus without downloading and executing all the data. chopsticks is only a mock client that it doesn’t verify anything at all

chopsticks is using some code from smoldot and smoldot implements light client
