### ISSUE TITLE
Not able to connect peers for mandala nodes

### ISSUE THREAD

**Issue by abhiyana** [AcalaNetwork/Acala#2705]
**Describe the bug**
I am trying to run the mandala node, but the peer, best, finalized is showing 0

**Expected Behavior**
Peers should be visible

**Current Behavior**
Peers are 0

**Steps to Reproduce**
1. Run the command
```docker run --platform=linux/amd64 acala/mandala-node --chain=mandala-latest -- --chain=rococo ```

**Additional context**

  - Node version:
  - OS: mac os
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address:
  - Logs. Please format it as `code blocks`

**Comment by zjb0807** [comment]
please use the command:
```
docker run --platform=linux/amd64 acala/mandala-node:2.22.0 --chain=/mandala.json -- --chain=/rococo-mandala.json
```
