### ISSUE TITLE
improve EVM trace logging format

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#2706]
Improve the EVM trace logging format to make it easier for people to trace EVM execution.

Ideally, all we need to do is to make a dev runtime build, and replay tx with Chopsticks, and getting some easy to understand call traces with arguments and return values and events and modified storages.

**Comment by Charlyn1234** [comment]
Thank u

**Comment by ermalkaleci** [comment]
[EVM+ Tracing](https://github.com/AcalaNetwork/chopsticks/blob/master/packages/chopsticks/src/plugins/trace-transaction/README.md) I guess this can be considered as complete
