### ISSUE TITLE
Decoding Metadata with subxt-metadata 

### ISSUE THREAD

**Issue by trevor-crypto** [AcalaNetwork/Acala#2708]
**Describe the bug**
I'm attempting to decode the Acala metadata from https://acala-rpc.dwellir.com with the [subxt-metadata crate](https://docs.rs/subxt/latest/subxt/metadata/struct.Metadata.html) but the current metadata doesn't seem to be able to to decode for some reason.

The error is not helpful:
```
DecodeError(Error { cause: None, desc: "Cannot
 try_into() to Metadata." })
```

**Expected Behavior**
The Acala metadata should be able to decode (like other parachains can)

**Reproduction**
1. Retrieve the metadata from the node with `state_getMetadata`
2. Call `let metadata = Decode::decode(encoded).unwrap();` and see the error.

Any tips would be appreciated. Thanks!

**Comment by xlc** [comment]
it is mostly likely subxt issue. could you provide a reproducible example?

**Comment by trevor-crypto** [comment]
@xlc Hi, please find a minimum reproduction here: https://github.com/trevor-crypto/acala-repro/blob/master/src/main.rs

I stored the metadata in a file called metadata.txt. It is take directly from this node - https://acala-rpc.dwellir.com/ - using the RPC call that I mentioned above

**Comment by trevor-crypto** [comment]
I get a more specific error when I change from `Metadata` to `RuntimeMetadataV14`

```
Error: Error { cause: Some(Error { cause: Some(Error { cause: Some(Error { cause: Some(Error
 { cause: Some(Error { cause: None, desc: "out of range decoding Compact<u32>" }), desc: "Co
uld not decode `Path::segments`" }), desc: "Could not decode `Type::path`" }), desc: "Could 
not decode `PortableType::ty`" }), desc: "Could not decode `PortableRegistry::types`" }), de
sc: "Could not decode `RuntimeMetadataV14::types`" }
```

**Comment by trevor-crypto** [comment]
After adding a dbg! to the subxt_metadata crate:
```rust
        metadata.map_err(|_e| {
            dbg!(_e);
            "Cannot try_into() to Metadata.".into()
        })

```

I can see the error!
```
_e = TypeNameNotFound(
    "ConvertEthTx",
)
```

**Comment by xlc** [comment]
That will be due to 
https://github.com/AcalaNetwork/Acala/blob/97bfc236ef6a0023aa0eadb9d55c38208f4cf00e/primitives/src/unchecked_extrinsic.rs#L43-L44

and the concrete type of ConvertEthTx is https://github.com/AcalaNetwork/Acala/blob/97bfc236ef6a0023aa0eadb9d55c38208f4cf00e/runtime/karura/src/lib.rs#L2302-L2303

I will still say it is subxt bug to not ignore it

**Comment by trevor-crypto** [comment]
@xlc Thanks! I will close this and continue the investigation and fix [here](https://github.com/paritytech/subxt/issues/1436)
