### ISSUE TITLE
unexpected result from `EVMTraceApi`

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/Acala#2783]
for [this transaction](https://blockscout.acala.network/tx/0x16a70b2202ceb4968dcd1c44ee782a145a51bf016b92cc871b25ca5723ceffc8), `evmTraceApi.traceExtrinsic` returns `revertReason: ERC20: insufficient allowance`, however it is actually a successful transaction.

Also, the result encoding seems to have some issue, with the revertReason being `\b�y�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1DERC20: insufficient allowance\x00\x00\x00`

## Reproduce
first run a chopsticks with tracing runtime
```ts
import '@acala-network/types'
import { withAcalaTypes } from '@acala-network/api';
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main() {
  const provider = new WsProvider('ws://127.0.0.1:8000');
  const api = await ApiPromise.create(withAcalaTypes({ provider }));

  const extrinsicHex = '0x41038400421c7a4b5839385d9453cca4dc139f9aba94e426befc5376dde8510b86d8a06803fa61d4950fe1841c7b274262de97c53628ff006da1b007d4bde9cfed6b1f2fdc063efe67b500d983c1602b63cc93ec2a7e3a938db7b0cd72da92a9af2e0650291b000c00820f007fe92ec600f15cd25253b421bc151c51b0276b7d11017b0472f000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000020a3d37de000007b276d2481742d4240000';
  
  const traceConf = { CallTracer: null };

  const res = await api.call.evmTraceApi.traceExtrinsic(extrinsicHex, traceConf);
  if (!res.isOk) {
    throw new Error(`traceCall: trace failed. Err: ${res.asErr.toString()}`);
  }

  console.log(res.asOk.asCalls.toJSON())

  await api.disconnect();
}

main();
```

result will be 
```
[
  {
    type: 'CALL',
    from: '0xc228264014732868016e1dc22c4c834e0d66aafd',
    to: '0x7fe92ec600f15cd25253b421bc151c51b0276b7d',
    input: '0x7b0472f000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000020a3d37de00',
    value: '0x0000000000000000000000000000000000000000000000000000000000000000',
    gas: 1020000,
    gasUsed: 1020000,
    output: null,
    error: null,
    revertReason: '\b�y�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1DERC20: insufficient allowance\x00\x00\x00',
    depth: 0,
    logs: [ [Object], [Object] ],
    calls: [ [Object] ]
  }
]
```

**Comment by shunjizhan** [comment]
also for [this dex.swap transaction](https://acala.subscan.io/block/6716773), I got error `Err: {"invalid":{"badProof":null}}`. Is it because this method only supports `evm.call` and `evm.callV2` extrinsic?

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/chopsticks/blob/8391fc807191aacc3e90ff29da7e7bbf42aaff94/configs/acala.yml#L5
`ACALA_BLOCK_NUMBER=6000106` 
Since the transaction depends on the current state, the block must be specified for tracing
