### ISSUE TITLE
homa predeploy reverts for old blocks

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/Acala#2789]
it's odd that `homa.getExchangeRate()` reverts for old blocks, did some binary search and the boundary seems to be block 444102: it reverts before block 4444102 and works afterwards.

I think we should already have homa up and running at block `4444102`, right?

```
{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [{
            "to": "0x0000000000000000000000000000000000000805",
            "data": "0xe6aa216c"
    },
    4444102
  ]
}

{
    "id": 0,
    "jsonrpc": "2.0",
    "result": "0x"
}
```

```
{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [{
            "to": "0x0000000000000000000000000000000000000805",
            "data": "0xe6aa216c"
    },
    4444103
  ]
}

{
    "id": 0,
    "jsonrpc": "2.0",
    "result": "0x00000000000000000000000000000000000000000000000001d4078ab2bc43d7"
}
```

**Comment by xlc** [comment]
can't find anything interesting around that block so not exactly sure why it failed
but in old days, we did some refactoring on the Homa pallet and the predeploy contracts so it wouldn't work for very very old blocks

**Comment by shunjizhan** [comment]
I believe it should be working not too long ago, since [this code](https://github.com/AcalaNetwork/telescope/blob/master/subql-old/src/mappings/mappingHandlers.ts#L13) worked before, which starts indexing at [block 4440289](https://github.com/AcalaNetwork/telescope/blob/master/subql-old/project.ts#L46)

**Comment by shunjizhan** [comment]
oh nevermind I think the first tx being indexed is at block `4538303`, so it might not actually hit that line until block `4538303`

**Comment by shunjizhan** [comment]
I will adjust the new indexer to start after `444103`, so it won't be an issue for now

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/master/packages/evm-subql/project-acala-840000.yaml

acala enabled the EVM after 840000

**Comment by shunjizhan** [comment]
> acala enabled the EVM after 840000
yeah the block number is `4444102`, after evm started

**Comment by shunjizhan** [comment]
@xlc should we keep the issue open? It does look like a bug, just not blocking us for now

**Comment by zjb0807** [comment]
The `STABLE_ASSET` predeploy contracts deployed on block 4444101 https://acala.subscan.io/extrinsic/4444101-2

**Comment by shunjizhan** [comment]
interesting, does it affect homa predeploy?

**Comment by zjb0807** [comment]
This Homa https://acala.subscan.io/extrinsic/4444103-2?event=4444103-11

you can check list here https://acala.subscan.io/event?module=evm&event_id=ContractPublished

**Comment by shunjizhan** [comment]
cool that makes sense
