### ISSUE TITLE
"Portal Bridge Not Swapping usdcet"

### ISSUE THREAD

**Issue by DylanCkawalec** [AcalaNetwork/Acala#2796]
**Describe the bug**
The swap states it runs through portal, but the report of when the usdcet never returns and it's unknown when or if there is a settlement taking place. 

**Expected Behavior**
The settlement should be sent to the wallet who made the bridge note

**Current Behavior**
You sign a message and do not see the transaction history to know if the settlement from portal bridge has occurred or not.

**Comment by xlc** [comment]
Can you provide the account, tx haha, and some screenshots?
