### ISSUE TITLE
Standarize asset selection

### ISSUE THREAD

**Issue by dudo50** [AcalaNetwork/Acala#2826]
**Describe the bug**
There are assets that have same name which makes it difficult for other devs to map them into SDKs

**Expected Behavior**
eg - first WETH can stay WETH and the other one can be for example WETH.e or something else, just do not allow duplicates please, as it complicates things a lot.

**Current Behavior**
Our XCM SDK fails with error because there are multiple assets of same symbol - eg. WETH
WETH - 0x5a4d6acdc4e3e5ab15717f407afe957f7a242578, WETH - 6

Expected status
Please differentiate assets in asset registry and do not allow for registering same asset symbol.

Thanks in advance!

**Comment by xlc** [comment]
well, you are going to be able to handle duplicated symbols eventually. but in this case, the AH WETH isn't used so we can rename it to WETHah if that helps

**Comment by dudo50** [comment]
Yes, any duplicit asset resolving will help. Thanks!
