### ISSUE TITLE
Make tx fee unit to be aUSD but payment token is still ACA

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#288]
We should make the tx fee unit to be aUSD instead of ACA to ensure consistence fee for user regardless ACA price.

e.g.

ACA price is $10 (from DEX), tx is $0.5, user will be charged with 0.05 ACA. If user have no ACA, other tokens (including aUSD) will be converted to 0.05 ACA to pay for the fee.

**Comment by hatred09** [comment]
Even when ACA is taken for tx fee, I noted that the balance of ACA not decreasing. Is the tx fee fixed or is it dependable?

**Comment by xlc** [comment]
It is likely the fee is low and not reflected on UI.

**Comment by hatred09** [comment]
Okay, thanks for the reply. Hope u show the tx fees before and after
transaction for it to be clear. Anyway great work on the project. Hope
everything will be perfect on launch date.

**Comment by wangjj9219** [comment]
I am worried that reliable prices cannot be obtained from dex in the early stage (there is no ACA trading pair, or the pool is dry), this maybe hinder transactions. We need to add some judgments to enable this mechanism, such as the depth of the ACA-aUSD trading pair

**Comment by wangjj9219** [comment]
Actually, the tx fee is not fixed in ACA, it's adjusted by a factor, which will change every block according to the fullness of the current block

**Comment by wangjj9219** [comment]
https://github.com/paritytech/substrate/blob/549050b7f1740c90855e777daf3f9700750ad7ff/frame/transaction-payment/src/lib.rs#L251-L255

**Comment by xlc** [comment]
We can't do this unless there is good liquidity for ACA/aUSD pair so close for now. May revisit this later.
