### ISSUE TITLE
Dex Module Design Draft

### ISSUE THREAD

**Issue by wangjj9219** [AcalaNetwork/Acala#31]
## dex module
参考uniswap的交易模式， 以aUSD为base token进行资产的去中心化交易

## Trait
+ Currency: MultiCurrency
+ Share
+ GetBaseCurrencyId: Get<CurrencyId>
+ GetExchangeFee: Get<FixedU128>

## Storage
+ LiquidityPool: double_map CurrencyId, CurrencyId => (Balance, Balance) 流动性池子
+ TotalShares: map CurrencyId => Share
+ Shares: double_map AccountId, CurrencyId => Share

## Call
+ swap_tokens(origin, supply: (CurrencyId, Balance), target: (CurrencyId, Balance))  
    - 用supply资产交换 target 资产， target.1 为能接受的换回的最低数量。
+ inject_liquidity(origin, currency_id: CurrencyId, amount: Balance, base_currency_amount: Balance) 
    - 向流动性池子注入资金，获得股权，amount 与 base_currency_amount分别是能够支付的other token 和 base token的上限
+ extract_liquidity(origin, currency_id: CurrencyId, extract_amount: T::Share)
    - 用股权赎回流动池资金

## Module: DexManager
实现 DexManager 以供拍卖模块调用

**Comment by xlc** [comment]
> LiquidityPool: double_map CurrencyId, CurrencyId => (Balance, Balance) 流动性池子

这个 key 只需要一个CurrencyId吧，base currency是固定的，不需要额外再传

> Shares: double_map AccountId, CurrencyId => Share

key 的顺序可以反过来，`double_map CurrencyId, AccountId => Share`，如果发生需要下架某个币的情况，可以快速遍历和移除相关的数据

inject_liquidity / extract_liquidity 名字要不要改成 add_liquidity / withdraw_liquidity ?

**Comment by xlc** [comment]
Done in #32
