### ISSUE TITLE
Transfer aUSD to Laminar Chain don't work see gif

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/Acala#324]
Hi! Balance on acala is correct but transfer not come!
![2020-07-27_11-08-36](https://user-images.githubusercontent.com/53031434/88508862-3a4aac00-cff9-11ea-8778-0535f9fa7ea1.gif)
my wallet 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ

**Comment by Madbustazz** [comment]
All fine! Thank you!

**Comment by qwer951123** [comment]
Hi! Transfer on laminar need some LAMI and aUSD ,you can get LAMI in https://discord.com/invite/VNjPcBZ .
