### ISSUE TITLE
Docker build missing ORML submodules

### ISSUE THREAD

**Issue by ltfschoen** [AcalaNetwork/Acala#332]
**My Acala Mandala Address: 5DRech3cqa15p3m7rgd1AoLbm8erSbdddUJLo18ESvuUbscN**

When users try to build Acala network using the Docker image using the latest 'master' branch (e.g. by running `docker build --tag acala:latest .`, they'll get the following error because the Dockerfile doesn't currently setup the ORML directories in the intermediate container.
```
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.45.0 (5c1f21c3b 2020-07-13)

error: failed to read `/acala/orml/currencies/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
The command '/bin/sh -c curl https://sh.rustup.rs -sSf | sh -s -- -y && 	export PATH="$PATH:$HOME/.cargo/bin" && 	rustup toolchain install nightly && 	rustup target add wasm32-unknown-unknown --toolchain nightly && 	rustup default stable && 	cargo build "--$PROFILE"' returned a non-zero code: 101
```

**Comment by zjb0807** [comment]
```
git submodule update --init --recursive
```
Add this before `cargo build`

**Comment by xlc** [comment]
Readme already includes the instructions this so I will close this.

**Comment by ltfschoen** [comment]
Thanks I understand now, I've adjusted my workflow to generate the submodules on the local machine using `git submodule update --init --recursive` before I build the Docker image with `docker build --tag acala:latest .`, so it's not necessary to generate the submodules in the Dockerfile since it'll use those already available on the local machine.
