### ISSUE TITLE
Calculate whether associated transaction fee exceeds User or System reward to be withdrawn and warn users 

### ISSUE THREAD

**Issue by ltfschoen** [AcalaNetwork/Acala#335]
**My Acala Mandala Address: 5F2QSwPHobet1pLFTEw6mkcT8bwZdEMmHfBGYPkiK7Pgxdex**

If I go https://apps.acala.network/deposit, and choose "Withdraw System Reward", and then select "ACA"
It displayed "0.000006 aUSD" for me, and that amount increases over time.
I assume this is calculated based on the "For System" "Total Reward", which increases over time i.e. 739.50 aUSD?

I clicked "Withdraw", and the fee for withdrawing was ~0.013 ACA (which I checked at https://acala-testnet.subscan.io/extrinsic/<EXTRINSIC_ID>.
Then when I go to the "Swap" screen, it shows the exchange rate of 0.013 ACA is 0.12441 aUSD.

So by me withdrawing my system reward prematurely (before it's value exceeded the transaction fee to withdraw it), i lost 20000x the reward value in aUSD just in the tx fee.

Is there an opportunity to warn the user before they withdraw their system or user reward if it'll mean they'll actually lose aUSD by doing so (i.e. just calculate that in the background), since doing so wouldn't make sense?

I think it would make sense to have this warning in the code since based on discussion with @xlc in the "Swap" section, we can't I swap a token for that same token (e.g. swap 1 DOT for 0.992943 DOT) and it gives an error, since doing so also doesn't make sense and isn't in the best interest of the user

**Comment by wangjj9219** [comment]
For these problems, the front end will do some restrictions or warnings
