### ISSUE TITLE
Inconsistent Rust nightly build versioning

### ISSUE THREAD

**Issue by ltfschoen** [AcalaNetwork/Acala#339]
**My Acala Mandala Address: 5F2QSwPHobet1pLFTEw6mkcT8bwZdEMmHfBGYPkiK7Pgxdex**

* test.yml [here](https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/test.yml)
* Pre commit hook [here](https://github.com/AcalaNetwork/Acala/blob/master/githooks/pre-commit)
* Travis file [here](https://github.com/AcalaNetwork/Acala/blob/master/.travis.yml)
* init.sh script [here](https://github.com/AcalaNetwork/Acala/blob/master/scripts/init.sh)
* update-mandala.sh [here](https://github.com/AcalaNetwork/Acala/blob/master/scripts/update-mandala.sh
* Makefile [here](https://github.com/AcalaNetwork/Acala/blob/master/Makefile)
* Dockerfile [here](https://github.com/AcalaNetwork/Acala/blob/master/Dockerfile)

If you want to use a different version of Nightly, then just perform a global find/replace to change `nightly-2020-06-04` to a more recent version consistently.

**Comment by xlc** [comment]
https://github.com/AcalaNetwork/Acala/pull/340#issuecomment-667638088

If it ain't broken, don't fix it.
