### ISSUE TITLE
RPC should support hex format number

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#349]
https://github.com/AcalaNetwork/Acala/blob/e97c45ea6f8fa8b58aab1b860889ed37f20a89a4/modules/dex/rpc/src/lib.rs#L19-L24

Should make it support hex format.

Substrate example:

https://github.com/paritytech/substrate/blob/270a992bf299cd41b2ed4e211814d2a958e3bfc8/primitives/runtime/src/generic/header.rs#L72-L86

Related https://github.com/polkadot-js/api/issues/2464

**Comment by wangjj9219** [comment]
closed by #352
