### ISSUE TITLE
Ensure all actions that locks or reserve funds updates system ref count

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#360]
`close_account` unreserve all funds and attempt to transfer all of them, so we need to make sure it doesn't unreserve or transfer suppose to be locked funds.

it does check `System::allow_death` so we need to make sure all pallets that locks fund or reserve them will update system ref count.

**Comment by apopiak** [comment]
`update_loan` does ref-counting, but does so incorrectly:
https://github.com/AcalaNetwork/Acala/blob/dcc3c1ea011e50b1a1923b1efc6ff5948a42a168/modules/loans/src/lib.rs#L260
The `inc_ref` condition is the same as the `dec_ref` condition.
