### ISSUE TITLE
Incentives

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#389]
Depends on https://github.com/open-web3-stack/open-runtime-module-library/issues/265

- module-incentives
  - Types
    - enum PoolId
      - Loans(CurrencyId)
      - DexIncentive(CurrencyId)
        - ACA reward
      - DexSaving(CurrencyId)
        - aUSD reward by CDP treasury
      - LDOT
    - impl PoolId
      - fn multiplier(self) -> FixedU128
    - struct OnAddLiquidity
    - impl Happened for OnAddLiquidity
    - struct OnRemoveLiquidity
    - impl Happened for OnRemoveLiquidity
    - struct OnUpdateLoan
    - impl Happened for OnUpdateLoan
  - Trait: orml_rewards::Trait
    - type LoansIncentivePool: Get\<AccountId>
    - type DexIncentivePool: Get\<AccountId>
    - type LDOTIncentivePool: Get\<AccountId>
    - type CDPTreasury: CDPTreasury
    - type AccumulatePeriod: Get\<BlockNumber>
  - Modules
    - impl RewardHandler
- module-dex
  - Trait
    - OnAddLiquidity: Happened\<(AccountId, CurrencyId, Share)>
    - OnRemoveLiquidity: Happened\<(AccountId, CurrencyId, Share)>
- module-loans
  - Trait
    - OnUpdateLoan: Happened<(AccountId, CurrencyId, Amount, Amount)>

**Comment by wangjj9219** [comment]
close by #395
