### ISSUE TITLE
AuctionManager: change withdraw / deposit

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#4]
https://github.com/AcalaNetwork/Acala/blob/67434adccd13ef5ff81fbcff3fcdcb2d570e32e2/modules/auction_manager/src/lib.rs#L161

https://github.com/AcalaNetwork/Acala/blob/67434adccd13ef5ff81fbcff3fcdcb2d570e32e2/modules/auction_manager/src/lib.rs#L167

https://github.com/AcalaNetwork/Acala/blob/67434adccd13ef5ff81fbcff3fcdcb2d570e32e2/modules/auction_manager/src/lib.rs#L178

The return values cannot be ignored because they may fail (shouldn't fail for `deposit`, but will fail on `withdraw` on malicious transaction).

Also better to use `transfer` over `withdraw` / `deposit` to avoid modify token total issuance.
The money should be transfer into / from the module's account, something like

https://github.com/paritytech/substrate/blob/73f4c118c07ff4a45c3acbbf62e8be96af96c28a/paint/treasury/src/lib.rs#L262-L264

Should have tests to ensure making bids without enough money won't be accepted.

**Comment by wangjj9219** [comment]
already check the bidder‘s balance before withdraw:
https://github.com/AcalaNetwork/Acala/blob/67434adccd13ef5ff81fbcff3fcdcb2d570e32e2/modules/auction_manager/src/lib.rs#L156-L157

not enough money test case:
https://github.com/AcalaNetwork/Acala/blob/67434adccd13ef5ff81fbcff3fcdcb2d570e32e2/modules/auction_manager/src/tests.rs#L34-L36

I will add module account to hold collateral and stablecoin balances in auction_manager and vaults

**Comment by wangjj9219** [comment]
resolve #12
