### ISSUE TITLE
Homa Protocol Redeem Fee

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#404]
From @Antonia-Chen :
https://acalaworkspace.slack.com/archives/CUWMD16T1/p1599148968001000

Main points:

- Inputs:
  - TargetFreePercentMin
  - TargetFreePercentMax
  - TargetFreeBufferPercent

- Unbond some DOT every day to gradually build up a buffer. 

```
struct FeeConfig {
	target_free_min: Permill,
	target_free_max: Permill,
	fee_min: Permill,
	fee_max: Permill,
}

trait FeeModel {
  fn get_fee(redeem_ldot: Balance, wait_era: EraIndex, current_free_percent: FixedU128, config: FeeConfig)
}
```

Make a simple linear FeeModel for now

**Comment by wangjj9219** [comment]
closed by #414
