### ISSUE TITLE
债务管理

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#45]
### 债务管理

债务分为三种：

- 全局债务
- CDP债务
- 系统债务 / 盈余

其中全局债务和系统债务都由 CDP Treasury 来管理，用户债务由 Vaults 管理

- 全局债务
  - 由 CDP Treasury 模块管理
  - 增发 aUSD 增加全局债务
  - 销毁 aUSD 减少全局债务
  - 所有 aUSD 的增发烧毁都必须由国库来完成
- 用户债务
  - 由 Vaults 模块管理
  - Valuts 管理用户债务和抵押品资产
  - 用户抵押资产铸造aUSD的流程
    - Vaults 把用户资产转移给模块账号，记录添加抵押品
    - Vaults 向 Treasury 申请资产
      - 添加全局债务
      - 铸造 aUSD
    - Vaults 添加CDP债务
  - 清偿债务赎回抵押资产流程
    - Vaults 通过 Treasury 销毁用户 aUSD
      - 减少全局债务
      - 销毁 aUSD
    - Vaults 转回抵押品给用户
- 系统债务 / 盈余
  - 每区块收取稳定费率利息
    - 通过增加债务单位汇率来增加所有CDP债务
    - 增加的部分计入系统盈余
  - 拍卖危险资产流程
    - 没收用户CDP资产
    - 转移CDP债务进入系统债务
    - 拍卖用户资产
    - 还回多余资产
    - 拍卖所得金额作为系统盈余
  - 每周期系统盈余和债务互相对抵

全局债务金额应等于：所有CDP债务金额 + 系统债务 - 系统盈余

回购ACA流程：

- 当系统盈余大于一定值的时候，发起回购ACA流程
- 系统盈余（一部分？）转换成 aUSD，同时添加全局债务
- 卖出aUSD，购买ACA
  - 具体方法待定，可以是拍卖，或者通过DEX
- 销毁回购的ACA

增发ACA流程：

- 当系统债务大于一定值的时候，发起增发ACA流程
- 增发卖出ACA，购买相当于系统债务的 aUSD
  - 具体方法待定，可以是拍卖，或者通过DEX
- 销毁 aUSD，减少相对应的全局债务
- 减少相对应的系统债务

**Comment by wangjj9219** [comment]
Dex依据乘积守恒计算交易金额， 流动池深度对交易滑点的影响很大，如果交易滑点过大，用户需要承担过大的交易损失。 能不能设定一个范围，在清算cdp时，如果交易滑点在范围内就直接同dex交易。 否则才创建抵押品拍卖

**Comment by xlc** [comment]
如果说还是会需要实现这个拍卖的流程的话，那一版就只支持拍卖就好了，二版可以再添加逻辑判断是否DEX或者拍卖。

我的想法是可以设定一个价格变化幅度，DEX自动交易直到价钱变化到这个度，或者卖出需要卖出的资产。如果还有剩余，进入拍卖阶段。
这样就是大部分小型清仓就直接DEX吃掉了，大型的才有拍卖流程。

**Comment by wangjj9219** [comment]
## auction_manager

- Types
	- struct <del>AuctionItem</del>
		- 改名 CollateralAuctionItem
	- struct DebitAuctionItem
		- 坏账拍卖
		- amount: Balance
		- target: Balance
		- start_time
	- struct SurplusAuctionItem
		- 盈余拍卖
		- amount: Balance
		- start_time
- Trait
	- GetNativeCurrencyId: Get<CurrencyId>
- Storage
	- <del>Auctions</del>
	- CollateralAuctions: map AuctionId => Option<CollateralAuctionItem>
		- 抵押品拍卖信息
	- DebitAuctions: map AuctionId => Option<DebitAuctionItem>
		- 系统债务拍卖信息
	- SurplusAuctions: map AuctionId => Option<SurplusAuctionItem>
		- 盈余拍卖信息
	- DebitInAuction: Balance
		- 拍卖中的系统债务
	- SurplusInAuction: Balance
		- 拍卖中的系统盈余
- AuctionManager
	- new_debit_auction(amount: Balance, target: Balance)
		- 创建系统债务拍卖
	- new_surplus_auction(amount: Balance)
		- 创建系统盈余拍卖
	- get_debit_in_auction() -> Balance
		- 获取拍卖中的系统债务数量

## cdp_treasury

- Trait
	- AuctionManagerHandler: AuctionManager
	- GetDebitBufferSize: Get<Balance>
	- GetSurplusBufferSize: Get<Balance>
	- GetDebitAuctionSize: Get<Balance>
	- GetSurplusAuctionSize: Get<Balance>
- Module
	- on_finalize
		- 抵消系统债务和盈余后，判断是否创建债务拍卖或盈余拍卖
