### ISSUE TITLE
'auction_collateral' weight is not constant

### ISSUE THREAD

**Issue by shaopengw** [AcalaNetwork/Acala#456]
Currently the default weight of `auction_collateral` is constant with huge amount of DB writes(`204`).

But the writes actually depend on dispatchable call parameters (such as `amount`) and auction parameters (such as collateral auction max size). The weight function need to be fixed.

https://github.com/AcalaNetwork/Acala/blob/2f1e20ccbefa3786cf4fe56bd4eeeff068d727f3/modules/cdp_treasury/src/default_weight.rs#L19-L23

**Comment by xlc** [comment]
Not real issue. This is a council only call anyway.
