### ISSUE TITLE
Emergency shutdown

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#49]
这里只考虑关停流程，如何启动关停流程属于治理设计的一部分，另行考虑

### 关停单一资产：

当某单个资产因为某些风险太高，可以启动关停单一资产流程

**流程：**

- 停止接受资产
  - 通过调整资产债务硬顶，不再接受更多该资产的抵押
  - 用户可以在这个阶段赎回资产
- 提升liquidation ratio
  - 每个block都提升liquidation ratio
  - 如果用户不主动关闭仓位的话，渐渐的所有仓位都会根据抵押率先后被平仓
- 强制清仓
  - 一定时间后，自动拍卖掉所有剩下的仓位

### 全局关停：

因为某种恶性原因，比如严重资金安全漏洞，恶意治理提案被通过等，可以启用全局关停流程避免情况恶化

**流程：**

- 快照最新Oracle价格
- 停止接受资产
  - 不再接受更多该资产的抵押
  - 仓位持有者可以将超额抵押的资产取回，不可直接赎回剩余部分
- 清算系统盈余 / 亏损
- aUSD持有者根据持有比率，按比例兑换全局抵押资产
- （以后）过渡为平行线程，只保留赎回资产功能

**Comment by wangjj9219** [comment]
## 全局关停

1. 关闭用户接口，锁定清算价格
2. 处理拍卖，有债务cdp，收集剩余抵押品，确定aUSD总量
3. 开启aUSD对剩余抵押物的兑换


### 阶段一 触发全局关停

1.关停用户对CDP的position调整（产生新债务和偿还债务）-- honzon 

2.关停 看护机/offchain-worker 对CDP的清算（至此不再产生新的抵押品拍卖）-- honzon

3.关停用户对CDP的position调整，停止创建 系统债务拍卖 和 系统盈余拍卖 -- cdp_treasury

4.停止稳定费的累积 -- cdp_engine

5.锁定 抵押物 aUSD的清算价格 -- price

### 阶段二 看护机/offchain-worker 开始处理CDP债务和拍卖

6.看护机/offchain-worker 取消进行中的坏账拍卖和盈余拍卖 -- auction，auction_manager  

7.看护机/offchain-worker 将尚在正向拍卖阶段的 抵押品拍卖（已经进入逆向的等其结束）取消，拍卖的抵押品交给 halt 模块。  -- auction_manager， halt

8.看护机/offchain-worker 对有债务的CDP进行处理（以清算价格拿走债务对应的抵押物），该有债务的CDP 变成 无债务CDP。 --  vault， halt

9.无债务CDP的所有者可以直接取回剩余抵押物 -- honzon，vault

### 阶段三 处理完毕，开启兑付

10.处理结束后，抵押品类的总债务为0，系统盈余为0 

11.开启最终兑付，销毁 aUSD兑付 halt中 一篮子抵押物
