### ISSUE TITLE
handle renBTC mint / burn decimals correctly

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#490]

**Comment by wangjj9219** [comment]
@qwer951123 
For the next testnet:
1. issue/burn RENBTC in decimal 8 instead of 18
2. fix the display for RENBTC on the front end
3. should adjust feed price for RENTBTC: 
         Currently, the decimal of RENBTC and other currencies in the system is 18, if the price of RENBTC is $20,000,  we feed Price::from_natural(20000).  However, the system does not know the decimal of each token, if there is a difference in decimal, it can be reflected in the feed price.  Here，the base decimal is 18, the actual price of RENBTC is Price::from_natural(20000),  the decimal of RENBTC is 8, the difference in decimal is  18 - 8 = 10,   the feed price should be the actual price multipled by 10**10 = Price::from_natural(20000* 10**10)
