### ISSUE TITLE
存款盈利--aUSD-renBTC质押问题

### ISSUE THREAD

**Issue by gzd1210** [AcalaNetwork/Acala#502]
![7a5fb16f1cccc7fd4aa9421972504f3](https://user-images.githubusercontent.com/73777151/97800210-6d42b280-1c6e-11eb-814a-a1e5bcad0e1b.jpg)
![c4c8c94edb0aa20f0469b6ec7794851](https://user-images.githubusercontent.com/73777151/97800212-703da300-1c6e-11eb-8aaa-7d30f4d5f262.jpg)
![ef36df7060bba1596ffb98160b6ce3a](https://user-images.githubusercontent.com/73777151/97800214-7af83800-1c6e-11eb-8c60-f324d1f28d5c.jpg)
余额显示低于0.00的时候，不能通过输入aUSD获取renBTC数值，只能通过输入0.00X的renBTC来取得aUSD数值。
我的地址为：5Fe7fjbujdH1bqTywhit69QjQJZeqUsXgegT4SULtfi1hfoG

**Comment by wangjj9219** [comment]
please report this issue to https://github.com/polkawallet-io/polkawallet-flutter
