### ISSUE TITLE
module-evm-accounts followup

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#513]
Followup of #512

- when an account is killed via `accounts.close_account)`, should clear the `Accounts` and `EvmAddresses` storage

https://github.com/AcalaNetwork/Acala/blob/c301ad36d03c447a70fad4fd70033bde1e9160ee/runtime/mandala/src/lib.rs#L1066

should be something like ` type KillAccount = (frame_system::CallKillAccount<Runtime>, module_evm_accounts::Module<Runtime>);`

- new trait in `orml-traits`:
  - trait MergeAccount
    - fn merge_account(source: AccountId, dest: AccountId) -> DispatchError
- orml-tokens implements `MergeAccount` that transfer all tokens from source to dest
- orml-currencies implements `MergeAccount` that calls `merge_account` from orml-tokens and transfer native token
- update module-evm-accounts Trait to add `type MergeAccount: MergeAccount`
- use `MergeAccount` to do the unreserve & transfer tokens 
- In module-accounts Module implement `MergeAccount` that use does the system ref check and reserve check
- Update module-accounts to use `MergeAccount` to handle close account
- In runtime `type MergeAccount = (Currencies, Accounts)`

**Comment by zjb0807** [comment]
Closes: #535
