### ISSUE TITLE
Error while doing make init

### ISSUE THREAD

**Issue by aj07** [AcalaNetwork/Acala#515]
Hi, 

I am trying to compile the Acala repo. I have tried with latest as well as 2020-10-06/01 build both. In both cases it is giving an error.

I am pasting the error link. Please, have a look and do let me know how it can be fixed. 

Link: https://imgur.com/a/HuffZFp

Thanks!

**Comment by xlc** [comment]
Use provide the error message instead of screenshots.

Try `rustup default nightly-2020-09-27`
