### ISSUE TITLE
Connecting metamask with acala network

### ISSUE THREAD

**Issue by aj07** [AcalaNetwork/Acala#516]
Hi,

I am trying to run acala network and connect with metamask. Getting some error. Would be great if you help me to clear it.

After doing the setup up of acala network. I am running cmd make run -- --ethereum-rpc

Just wondering is that cmd right ? or I am doing something wrong. 

![Screenshot from 2020-11-05 19-09-29](https://user-images.githubusercontent.com/9623159/98258958-7314fc80-1fbc-11eb-8b98-cd5adf08748c.png)

**Comment by xlc** [comment]
`--ethereum-rpc` is the additional rpc you needed. Try `cargo run -- --dev --ethereum-rpc`

And chain id is a number, not hex. i.e. without `0x`

**Comment by aj07** [comment]
Hi, @xlc 

Its giving error around it.

 Finished dev [unoptimized + debuginfo] target(s) in 0.51s
     Running `target/debug/acala --dev --ethereum-rpc`
error: Found argument '--ethereum-rpc' which wasn't expected, or isn't valid in this context

USAGE:
    acala --dev

**Comment by xlc** [comment]
You need to use `evm` branch

**Comment by aj07** [comment]
Hi,

I checkeout to evm branch. Able to run cargo run -- --dev --ethereum-rpc
 
But when trying to connect with metamask, its giving same error. 

RPC URL:  http://localhost:9933   |   http://localhost:9933/
ChainId: 10042

I think my rpc url is correct but still its saying Could not fetch chain ID. Is your RPC URL correct?

**Comment by xlc** [comment]
Can you try `curl http://localhost:9933/health`

**Comment by aj07** [comment]
Ah.. i see. Its inactive
curl: (7) Failed to connect to localhost port 9933: Connection refused


I tired to fix this by using this doc. https://askubuntu.com/questions/1259860/on-ubuntu-20-04-how-do-you-open-a-port-in-the-firewall  
But, still this is giving an error.

**Comment by xlc** [comment]
is it running inside vm or docker or a remote server?

**Comment by aj07** [comment]
![Screenshot from 2020-11-06 12-28-37](https://user-images.githubusercontent.com/9623159/98326227-b490c080-202b-11eb-9d77-3379760fab9a.png)

I am running it on bare metal. But docker is been installed. I tried by starting and stopping docker but it didn't worked out

**Comment by xlc** [comment]
Try `cargo run -- --dev --ethereum-rpc --tmp --rpc-cors=all --rpc-external` and make sure you can connect to the node using https://console.acala.network/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer

**Comment by arunjot12** [comment]
Can you tell me about the EVM branch? Has it been renamed? On which branch or tag was this issue properly fixed in Acala
