### ISSUE TITLE
Dorahacks Bounty

### ISSUE THREAD

**Issue by jiangfuyao** [AcalaNetwork/Acala#641]
### Option 1
Build an order-based exchange that allows people to create, view, and take orders to trade different tokens. To maximize the chance of winning, please implement some additional features. Here are some examples, but use your imagination: 
- A nice front-end for a user to interact with
- On-chain automatic order-matching (please consider the complexity and on-chain execution performance) 
- Off-chain automatic order-matching via off-chain workers
- Advanced order types such as limited order, or order with an expiration 
- Auction
- ...  

### Option 2
Build a dashboard for Acala that allows people to view the data of Acala's Dapps. To maximize the readability and validity of the data of Acala, please create some charts for the analysis base on the data of Acala and implement some additional features to control the risk of the system. Here are some examples, but use your imagination: 
- The parameters of Acala's Dapps
- The ratio of collateral 
- The data of users
- The list of collateral
- The parameters of risk 
- ...

### Bounty rule
The Acala team will base on the completeness and usability of the entries to judge, if the entry satisfies the requirement of the Acala team, the team will be rewarded 2000 USD worth of ACA.   

### Getting Started 
- Join the Acala Discord (https://discord.com/invite/6QHVY4X)
- Open Runtime Module Library (ORML) workshop: 
   - Video  （https://www.crowdcast.io/e/axvfinsv/19）
   -  Github （https://github.com/xlc/orml-workshop）
   - Video: Build Cross-chain DeFi with Acala (https://www.crowdcast.io/e/defi-with-acala)
- Open Runtime Module Library (https://github.com/open-web3-stack/open-runtime-module-library)
- Substrate Node Template (https://github.com/substrate-developer-hub/substrate-node-template)
- Polkadot-JS (https://polkadot.js.org/docs/api/)
- Acala Wiki (https://wiki.acala.network/)
- Acala Apps (https://apps.acala.network/)
- Acala JS SDK (https://github.com/AcalaNetwork/acala.js)

**Comment by bleemer4** [comment]
Hi, we provide a NFT-order exchange for Option 1.
Code: https://github.com/DNFT-Team
HackerLink: https://hackerlink.io/buidl/53

**Comment by xlc** [comment]
@bleemer4 Thanks for the submission.

Please provide more detailed documents on following topics:

- The goal of this project
- What is implemented
- How to interact with your chain
- Some screenshots of each steps
- How is your implementation achieve the goal
- What are future works

**Comment by bleemer4** [comment]
> @bleemer4 Thanks for the submission.
> 
> Please provide more detailed documents on following topics:
> 
> * The goal of this project
> * What is implemented
> * How to interact with your chain
> * Some screenshots of each steps
> * How is your implementation achieve the goal
> * What are future works

Hi @xlc, Thanks for your reply.
We have updated a  [doc](https://github.com/DNFT-Team/Acala-Dorahacks-Bounty/blob/main/README.md). 
We will continue to follow Acala and improve our project.
Many thanks.

**Comment by wangjj9219** [comment]
> > @bleemer4 Thanks for the submission.
> > Please provide more detailed documents on following topics:
> > 
> > * The goal of this project
> > * What is implemented
> > * How to interact with your chain
> > * Some screenshots of each steps
> > * How is your implementation achieve the goal
> > * What are future works
> 
> Hi @xlc, Thanks for your reply.
> We have updated a [doc](https://github.com/DNFT-Team/Acala-Dorahacks-Bounty/blob/main/README.md).
> We will continue to follow Acala and improve our project.
> Many thanks.

Hi, I see you guys have implemented a NFTs management module, and designed some mechanisms for the storage rent/tax of NFTs, include a DAO to govern these tax/rent. I think you did a good job, but option 1 prefer a matchmaking transaction system for fungible tokens，and I didn't see matchmaking except for taking order.

**Comment by bleemer4** [comment]
Thanks for your advice. Our order matchmaking module is almost done and under testing. Since we noticed the Bonuty too late, and close to the  deadline, we applied the ready part.
I wonder If we have a chance to complete? or we'll participate in next Bonuty.
We'll keep looking on Acala.
