### ISSUE TITLE
Migrate modules to use `pallet!` macro

### ISSUE THREAD

**Issue by wangjj9219** [AcalaNetwork/Acala#670]
About how to migration: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines
about how to review a migration: https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

Schedule:

- [x] auction_manager
- [x] cdp_engine
- [x] cdp_treasury
- [x] currencies
- [x] dex
- [x] emergency_shutdown
- [x] evm_accounts
- [x] evm_bridge
- [x] evm
- [x] homa
- [x] honzon
- [x] incentives
- [x] loans
- [x] nft
- [x] nominees_election
- [x] polkadot_bridge
- [x] prices
- [x] staking_pool
- [x] transaction_payment

**Comment by shaopengw** [comment]
I'm working on `evm`, `evm_bridge`, `evm_accunts` migration.

**Comment by shaopengw** [comment]
Done.
