### ISSUE TITLE
Treasury address uses a different address with other networks, for avoid confusion.

### ISSUE THREAD

**Issue by 0xthreebody** [AcalaNetwork/Acala#744]
https://kusama.subscan.io/tools/ss58_transform?input=0x6d6f646c70792f74727372790000000000000000000000000000000000000000

Most treasury public key is `0x6d6f646c70792f74727372790000000000000000000000000000000000000000`.

Should different treasury public keys be set up for different networks? Pave the way for future dSWF.

If dSWF only controls cross-chain assets in its own chain, there is no need to set a different public key. Such as LDOT.

And pass msg to other chains through XCMP and use a new proxy treasury account, not need to set up a different public key, also.

But use the same treasury account, in other chains through XCMP, needs a different address.

**Comment by xlc** [comment]
Yeah we should be able to get all our system address with aca prefix
