### ISSUE TITLE
module-homa-validator-list

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#757]
- orml-traits
  - Types
    - trait Contains\<T>
      - fn contains(t: &T) -> bool
- module-homa-validator-list
  - Types
    - struct NominationInfo
      - bonded: Share
      - unbonding: Option<(Share, BlockNumber)>
      - free: Share
    - struct SlashInfo
      - validator: RelaychainAccountId
      - relaychain_token_amount: Balance
        - make it compact
  - Config
    - type LiquidTokenCurrency: BasicLockableCurrency
    - type RelaychainAccountId
    - type MinNominateAmount: Get\<Balance>
    - type BondingDuration: Get\<BlockNumber>
      - withdraw need to wait at least this many blocks
      - this should be the max time required to have > 1/3 Homa Council to execute freeze
      - i.e. if slash happened, validator may try to unbond & withdraw to avoid penalty and Council needs to freeze the withdraw before BondingDuration ends
    - type FreezeOrigin: EnsureOrigin
      - \> 1/3 Homa Council
    - type SlashOrigin: EnsureOrigin
      - \> 1/2 Homa Council
    - type OnSlash: Happened\<Balance>
      - This should connect to StakingPool to add debits and when it receives the actual slash from relaychain, reduces debits
  - Storages
    - Nominations: double_map AccountId, RelaychainAccountId => Option\<NominationInfo>
    - ValidatorBacking: map RelaychainAccountId => (Balance, Share)
      - total liquid token balance in the pool including unbonded, total share
    - FronzenValidators: map RelaychainAccountId => ()
  - Calls
    - fn nominate(origin, validator: RelaychainAccountId, amount: Balance)
      - lock LDOT to nomiante a validator
      - mint validator pool share
      - update `Nominations` and `ValidatorBacking`
    - fn unbond(origin, validator: RelaychainAccountId, shares: Share)
      - unnominate validator and start unbonding LDOT
      - update `Nominations` and `ValidatorBacking`
      - if already have unbonding one, merge with it and extend the unbond time
    - fn rebond(origin, validator: RelaychainAccountId, shares: Share)
      - move unbonding shares to bonded
    - fn withdraw(origin, validator: RelaychainAccountId)
      - ensure validator is not frozen
      - burn validator share
      - withdraw all free LDOT
    - fn freeze(origin, validators: Vec\<RelaychainAccountId>)
      - ensure FreezeOrigin
      - set frozen for each validators
    - fn thaw(origin, validator: Vec\<RelaychainAccountId>)
      - ensure SlashOrigin
      - clear frozen for each validators
    - fn slash(origin, slashes: Vec\<SlashInfo>)
      - ensure SlashOrigin
      - for each slashes
        - calculate how much LDOT to burn and burn it from validator backing
        - update total slashed amount
      - T::OnSlash(total_slashed_amount)
      - This should burn LDOT & reduce DOT balance so in the end the LDOT/DOT rate shuold remains the same
  - Module
    - impl Contains\<RelaychainAccountId>
      - return true if given account is registered valdiator
      - NomineesElection should use this filter validators

This will require validators to lock some LDOTs into insurance fund and if slash happened, HomaCouncil can burn those LDOT to compensate LDOT holders.

Later if needed, we can redirect some rewards into the insurance fund so people offer insurance will have extra rewards (with risk of been slashed).

**Comment by xlc** [comment]
When slash is detected, Homa council will freeze validator bond. If slash is cancelled by relaychain council, homa council will thaw the validator bond. If slash is applied, validator bond will be slashed & burned to ensure LDOT/DOT rate stay the same.

At later stage, when XCM event notification is ready, we can automate this process so no need Homa council's involvement.

**Comment by zjb0807** [comment]
Closed by #768
