### ISSUE TITLE
RPC error (NoPermission - Acala-node only)

### ISSUE THREAD

**Issue by boyswan** [AcalaNetwork/Acala#783]
I'm running Acala-node, and can successfully interact with preloaded smart contracts, however after deploying my own I get an error when I try to interact with it.

```
  const contract = await ContractFactory.fromSolidity(ABI)
    .connect(bob)
    .deploy();

  let addr = await bob.getAddress();
  let balance = await contract.balanceOf(addr);

  console.log(balance.toString());
  ```
  
  Errors with:
  
  ```
  2021-03-03 11:19:57        RPC-CORE: call(data: CallRequest, at?: BlockHash): Raw:: -32603: execution fatal: DispatchError::Module { index: 58, error: 2, message: Some("NoPermission") }
An unexpected error occurred:

Error: -32603: execution fatal: DispatchError::Module { index: 58, error: 2, message: Some("NoPermission") }
    at RpcCoder._checkError (/Users/jack/Desktop/nft_acala/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
   ``` 
   
This error doesn't happen if I run the node via the docker container `acala/acala-node:latest`, but it doesn't have the latest preloaded smart contracts that I want to interact with.

**Comment by zjb0807** [comment]
Can you try `https://github.com/AcalaNetwork/evm-examples/blob/master/erc20/test/BasicToken.test.ts`?
If it not work, please show me the git hash and commands

**Comment by boyswan** [comment]
Ahh my bad, I was running with `make run` instead of `make run-eth`. Thanks for pointing me in the right direction
