### ISSUE TITLE
Update tokenDecimals & tokenSymbol

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#792]
Update tokenDecimals & tokenSymbol in chain properties to include all our other tokens & decimals

https://github.com/AcalaNetwork/Acala/blob/0a3cec5e09fbe0a9d8bc1cfe656f16f739e1aebb/bin/acala-dev/service/src/chain_spec/mandala.rs#L23-L25

**Comment by wangjj9219** [comment]
What are the decimals of PLM, PHA and SDN?

**Comment by xlc** [comment]
https://github.com/paritytech/substrate/blob/master/ss58-registry.json

SDN should be same as PLM
