### ISSUE TITLE
Develop RPC to estimate weights by dry run transaction and report used weight

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#814]

**Comment by xlc** [comment]
Doesn't the RPC from transaction payment does this? https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/rpc/runtime-api/src/lib.rs

**Comment by ermalkaleci** [comment]
@xlc This end up calling `get_dispatch_info` which returns weight specified in `#[pallet::weight]`. It doesn't execute anything so no measurement is done here

**Comment by xlc** [comment]
In that case https://github.com/paritytech/substrate/issues/7555 can solve the issue. The extrinsic success / failed event will have actual weight.
