### ISSUE TITLE
Perpetual KSM/DOT

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#820]
# Perpetual KSM/DOT

## Background

Kusama is going to have new financial product: [Gilts](https://github.com/paritytech/polkadot/pull/2587). Polkadot is likely going to have it once it is proven useful on Kusama.

Gilts are non-transferable, inflation resistant KSM/DOT derivatives. The number of KSM/DOT in gilt will increase exact the same rate as network inflation rate. Gilt cannot be used for governance / staking / any onchain activities and can only be redeemed to KSM/DOT after the expiration period. It is a "just a dumb store of value". Gilt will enjoy the interest rate that is same as network inflation rate without any risk of slashing. This makes it a perfect candidate for DeFi collateral that needs to be locked for potentially long period of time.

There is only limited supply of Gilts to ensure it don't conflict with network security and therefore people needs to bid for locking period to create new gilt. The longer the locking period, the higher priority the bid to be processed.

## Overview

Acala is going to implement Perpetual Relaychain token (PKSM / PDOT) to allow DOT holder on Acala to generate gilts and use it to participate DeFi application. At same time, the P token are also transferable and fungible to solve the iliquid limitation.

## Basic Design

- module-perpetual-token
  - Calls
    - place_bid(origin, amount: Balance, duration: u32)
      - Reserve DOT & reserve this bid
      - Place this bid on relaychain via XCM
      - Mint a gilt placeholder NFT for owner
    - retract_bid(origin, amount: duration: u32)
      - Send XCM to retract bid
      - XCM response should indicate if this successes, and if yes, unreserve DOT
    - note_issued(origin, index: TokenIndex)
      - Send XCM to query if gilt is processed on relaychain
      - Record this request
      - Upon response, if this gilt is processed, convert the placeholder NFT into Gilt NFT with expiration date & proportion
    - thaw(origin, index: TokenIndex)
      - Transfer in the NFT
      - Send XCM to thaw gilt
      - XCM response should indicate if this successes, and if yes, burn NFT and unreserve & mint corresponding DOT

## Maybe in future

Convert NFT gilt to fungible ptoken so it can play nicely with other protocols that doesn't support NFT

  - claim_ptoken(origin, index: TokenIndex)
    - Check if Gilt NFT is expired
    - If expired, burn it, and mint PToken to owner
  - redeem(origin, ptoken_amount: Balance)
    - Burn ptoken
    - Send XCM message to relaychain to ask for total issuance & treasury pot size
    - Calculate how much relaychain to mint to user & mint.
    - Note we don't redeem gilt on relaychain. So we will have some relaychian token debit.
    - Record relaychain token debit & deposit ptoken to pool
  - buy_ptoken(origin, relaychain_token_amount: Balance)
    - Estimate relaychain total issuance - treasury pot size
      - If last fetch is < x days, use 20% APY inflation rate to estimate
      - Else send XCM to fetch total issuance & treasury pot size
    - Calculate how much ptoken to provide (with fee deduced), and if we have this amount of ptoken in pool, send it to user
    - Burn the relaychain token, and reduce pool debit
    - Note we always overestimate so give less ptoken. The less part can be considered as part of the fee.

Still need to think about cross-chain interaction & optimziation to reduce crosschain messages.

On crosschain transfer relaychain token to other chains, when we don't have enough token, redeem some gilt and adjust ptoken pool size & debit.

ptoken value could go down when slash happens so needs some considerations.

**Comment by xlc** [comment]
The expiry of gilt could be multiple years so V1 doesn't need the NFT redeem to fungible token part.

**Comment by AlistairStewart** [comment]
>Gilt cannot be used for governance

I believe that Gilts will be usable for governance. Like with parachain desposits, it's a good idea to keep tokens held by entities with a long term interest in the sucess of the network involved with governance.

Your idea should work. I expected someone to suggest this.

**Comment by xlc** [comment]
At least for the current implementation, reserve is used instead of lock, so it cannot be used for governance.
Lock cannot be used because it is not exclusive. There needs some major refactoring to decouple between Currency & governance related pallets in order to make this possible.

But of course if gilt can be used governance, it won't be hard for us to implement a feature to allow gilt holder to participate.

**Comment by Tomen** [comment]
You might want to replace the word "inflection" with "inflation"
