### ISSUE TITLE
NativeCurrency is hard-coded to ACA

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#837]
Define native currency token symbol as parameter `NativeTokenSymbol: Get<TokenSymbol>` and use that instead of `CurrencyId::Token(TokenSymbol::ACA) =>` to enable using `KAR` on Karura runtime

**Comment by ermalkaleci** [comment]
@xlc another way will be `use primitives::currency::{ACA, KAR};` and then check `ACA | KAR => `

**Comment by xlc** [comment]
Where is the code using ACA?

**Comment by ermalkaleci** [comment]
@xlc in MultiCurrency implementation https://github.com/AcalaNetwork/Acala/blob/master/modules/currencies/src/lib.rs#L192

**Comment by zjb0807** [comment]
Closes by #845
