### ISSUE TITLE
Acala Mandala TestNet T6

### ISSUE THREAD

**Issue by Maik00Ita** [AcalaNetwork/Acala#862]
Hello Acala Team!
Maybe i wrong somethings, but probably we have some little bugs (very little)!

- in the oracle page is not possible to come back once you choose one option (ren or polkabtc)
- when push max in the import the fees are not calculated as subracted, example: if my max import is 100 and my fee is 1 i need to have 101 token not 100, so my maximum should be 99, in that way you avoid token loss
- now do not refresh the page any time you doing transaction, you didn't see the transaction done
- a good way to burn token should be to create an account connected to your wallet address and give a choise about some NFT as picture close to your nickname
- sometimes loan are not created, error  10705

Hope to be helpful

**Comment by ZQ-L** [comment]
Hello Acala Team!
 During the test, I found that LP tokens will not be displayed in the wallet. The specific number of LP tokens will only be displayed when you want to conduct liquidity mining!
Why is there such a design? I feel that it may cause inconvenience to users!
