### ISSUE TITLE
"unknownTokens.BalanceTooLow" when sending xcm transferring

### ISSUE THREAD

**Issue by h4x3rotab** [AcalaNetwork/Acala#866]
This was triggered when on a local Rococo testnet. We call `xTokens.transferToParachain` to send some ACA to Phala parachain testnet. The deposit XCM **did arrive** Phala parachain, and the extrinsic got executed successfully, which means the cross chain messaging worked generally. However we got the error from the logs on the Acala side. It indicates something wrong was happening.

We set up the environment with polkadot-launch, with Acala deployed as Parachain 666 and Phala deployed at as Parachain 30. The code is all at the latest master branch.

## Input transactions

Generated by [this script](https://github.com/Phala-Network/phala-blockchain/blob/master/scripts/js/transferFromAcala.js).

```json
[
  {
    "chainId": {
      "paraChain": 666
    },
    "currencyId": "0x414341"
  },
  30,
  {
    "x1": {
      "accountId32": {
        "network": {
          "any": null
        },
        "id": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
      }
    }
  },
  "0x00000000000000000017a93c16344000"
]
```

### acalaTreasury.Deposit

Some funds have been deposited. [deposit] 

```
Balance
0.0180
```

3,469-8

### xTokens.TransferredToParachain

Transferred to parachain. [x_currency_id, src, para_id, dest, dest_network, amount] 

```
XCurrencyId
{
  chainId: {
    ParaChain: 666
  },
  currencyId: ACA
}

AccountId
ALICE
5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY

ParaId
30

MultiLocation
{
  X1: {
    AccountId32: {
      network: {
        Any: null
      },
      id: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
    }
  }
}

Balance
666.0000
```

3,469-7

### xcmHandler.Success

Some XCM was executed ok. 

```
Hash
0x4600539c7dc8506fd3c26203dedf64d3bc912d67d26c1f8b64e17310a28e6b30
```

3,469-6

### xcmHandler.HrmpMessageSent

An HRMP message was sent to a sibling parachain. 

```
Hash
0x8dd66677eacf5d3fd27fe8965ad4843a357e158abf3ccec74eca4863e2763212
```

3,469-5

### currencies.Deposited

Deposit success. [currency_id, who, amount] 

```
CurrencyIdOf
{
  Token: ACA
}

AccountId
5Eg2fn…hAU2xS
5Eg2fnsgM9eadmor2D6R4mc4N4UhfzhTNJNctKi2dHhAU2xS

BalanceOf
666.0000
```

3,469-4

### currencies.Withdrawn

Withdraw success. [currency_id, who, amount] 

```
CurrencyIdOf
{
  Token: ACA
}

AccountId
ALICE
5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY

BalanceOf
666.0000
```

3,469-3

### unknownTokens.WithdrawFailed

Withdraw failed. [asset, from, error] 

```
MultiAsset
{
  ConcreteFungible: {
    id: {
      X1: {
        GeneralKey: ACA
      }
    },
    amount: 6,660,000,000,000,000
  }
}

MultiLocation
{
  X1: {
    AccountId32: {
      network: {
        Named: acala
      },
      id: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
    }
  }
}

DispatchError
{
  Module: {
    index: 60,
    error: 0
  }
}

type
unknownTokens.BalanceTooLow
details
 The balance is too low.

```

3,469-2

**Comment by shaunxw** [comment]
In currency adapter unknown token withdraw was always tried firstly, and it [deposits an `WithdrawFailed` event](https://github.com/open-web3-stack/open-runtime-module-library/blob/3a77e1a96aa49af09f4c5584ff212673132c5456/unknown-tokens/src/lib.rs#L120) if failed.

This is no actually state error in this case, all balances are maintained well. However the `WithdrawFailed` event might be confusing to users.

**Comment by xlc** [comment]
there shouldn't be WithdrawFailed event if withdraw did not fail.

**Comment by shaunxw** [comment]
Yep in general there should be no failure events if the "withdraw" doesn't fail. However the currency adapter cannot tell if the transact is about known token or unknown one, so it has to try withdraw on both. Meanwhile unknown token can't know if both transact failed and thus the "withdraw" failed, so it record events as long as if *it's* withdraw try fails.

The best way to solve this might be a compromise that we don't deposit failure events at all. Instead, an more implicit `XCMError::TransactAsset` implies both try failed.
