### ISSUE TITLE
Integration tests for Karura

### ISSUE THREAD

**Issue by shaunxw** [AcalaNetwork/Acala#899]

**Comment by xlc** [comment]
We have some integration tests for Mandala. We want to run most of then for Karura as well.

One way is to do something similar to pallet-balances

https://github.com/paritytech/substrate/blob/master/frame/balances/src/tests.rs
https://github.com/paritytech/substrate/blob/master/frame/balances/src/tests_composite.rs
https://github.com/paritytech/substrate/blob/master/frame/balances/src/tests_local.rs
