### ISSUE TITLE
CurrencyId decode is broken

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/Acala#918]

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/predeploy-contracts/blob/78207075331d18007fa73a63be88f2f94aef0ed8/generate/generate.js#L59-L60

This can fix it. I still have some problems in debugging, so I haven't merged it yet.

**Comment by ermalkaleci** [comment]
@zjb0807 why not keep currency_id at the end?
