### ISSUE TITLE
Compound Gateway Startport pallet

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#924]
# module-starport

- Types
  - type GatewayAccountId = ecdsa::Public
  - type TrxRequest = BoundedVec\<u8>
  - type GatewayNotice = BoundedVec\<u8>
  - type GatewaySignature = ecdsa::Signature
- Config
  - type Currency: MultiCurrency
  - type SupportedCurrencyId: Filter\<CurrencyId>
  - type CashCurrencyId: CurrencyId
  - type PalletId: PalletId
  - type AdminOrigin: EnsureOrigin
- Storage
  - SupplyCaps: map CurrencyId => Balance
  - InvokedNoticeHashes: map H256 => ()
  - Authorities: BoundedVec\<AccountId>
- Calls
  - fn lock(origin, amount: Balance, currency_id: CurrencyId)
    - lockTo(origin, amount, currency_id, origin)
  - fn lockTo(origin, amount: Balance, currency_id: CurrencyId, recipient: GatewayAccountId)
    - ensure signed
    - ensure `SupportedCurrencyId::fitler(currency_id)`
    -  if `currency_id == Cash`
       - burn
       - emit LockCash
    - else
      - ensure did not exceed supply caps
      - transfer token to pallet account
      - emit Lock
  - fn exec_trx_request(origin, req: TrxRequest)
    - ensure signed
    - emit ExecTrxRequest
  - fn invoke(origin, notice: GatewayNotice, signatures: BoundedVec\<Signature>)
    - ensure signed
    - validate signatures
    - execute notice
  - fn invokeChain
    - TODO: this needs more consideration on upstream, see below

## module-cash-token

- Note
  - Should try to reuse all the rebase logic from Gateway to avoid duplicated code
  - Implement Currency trait families
  - Implement additional admin API `set_future_yield`

References:

- Gateway Docs: https://docs.google.com/document/d/1bp4uLYHt0_lUNO3dveFGelXYAC-M7RojqY-5jPDyUlM/edit#heading=h.ifxd6vwkc2cm
- Solidity Starport: https://github.com/compound-finance/gateway/blob/develop/ethereum/contracts/Starport.sol

Upstream TODOs:

- ChainAsset::Dot
- Notice::Dot
- When can we purge `InvokedNoticeHashes` ?
- Need better way to proof old notice
  - Upon change authorities, all old notices cannot be executed until one notice signed with new authorities
  - ~should just ask new authorities to sign the notice offchain via RPC~
  - ~the proof can be verified offchain~
  - We should just use a better authenticated data structure
- For system notices (change authority, set future yield, set supply cap), should have an unified format
  - otherwise it needs to emit once notice per chain
- How does a notice refer parent hash from another chain? Some refactor required for `LatestNotice`

TODOS:
- XCM handling
- Notice execution
- Custom RPC

**Comment by syan095** [comment]
Progress update:
Initial commit for Prototype is complete.
https://github.com/AcalaNetwork/Acala/pull/1099

TODOS on Acala side:
* Replace Signature verification to EvmAddress (it is using plaining Substrate AccountId matching)
* How to do cross-chain communication between Acala and Compound
* Compound-Cash module is just a place holder at the moment.
    - Need to add timestamp + balance for interest calculation
    - Need to add arithmetic  for interest calculation
* Need to update Genesis config to set initial authorities correctly.
