### ISSUE TITLE
How does 'lock_price'  in prices pallet work？

### ISSUE THREAD

**Issue by RainFallsSilent** [AcalaNetwork/Acala#963]
I think "lock_price" may cause some problems:
When the price feeder goes wrong or the currency price is maliciously manipulated, we may use "lock_price" to lock the price?
but "lock_price" will aggregate prices from existing values which include abnormal prices. 
Does it seem that we may get the wrong price when calling "get_price"?

**Comment by xlc** [comment]
it is designed to be used on during emergency shutdown
