### ISSUE TITLE
Version cargo

### ISSUE THREAD

**Issue by Daelon02** [AcalaNetwork/Acala#970]
Hello, what version of rust is needed for build?

**Comment by zjb0807** [comment]
You can see github ci.
https://www.github.com/AcalaNetwork/Acala/tree/master/.github%2Fworkflows%2Ftest.yml

**Comment by Daelon02** [comment]
> 
> 
> You can see github ci.
> https://www.github.com/AcalaNetwork/Acala/tree/master/.github%2Fworkflows%2Ftest.yml

Thanks)
