### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Daelon02** [AcalaNetwork/Acala#971]
Hi, when i trying build, i have error when start build js-sys, i take cargo version from https://www.github.com/AcalaNetwork/Acala/tree/master/.github%2Fworkflows%2Ftest.yml

**Comment by xlc** [comment]
what’s the error and how did you build it?

**Comment by Daelon02** [comment]
> 
> 
> what’s the error and how did you build it?

From cargo build --release, but now another error [
![Screenshot_3](https://user-images.githubusercontent.com/63471940/116757605-0fbdd180-aa17-11eb-977e-7978ca461085.png)
]

**Comment by xlc** [comment]
can you provide all the logs

**Comment by Daelon02** [comment]
> can you provide all the logs

You mean from RUST_BACKTRACE?

**Comment by xlc** [comment]
no. I mean everything coming out from `cargo build --release`

**Comment by Daelon02** [comment]
Now, another errors, I try implement staking-pool in our project, but have this errors 
[text.txt](https://github.com/AcalaNetwork/Acala/files/6419465/text.txt)

**Comment by xlc** [comment]
this is dependency version mismatch and doesn't looks like coming Acala

if you need Substrate support, ask here: https://app.element.io/#/room/!HzySYSaIhtyWrwiwEV:matrix.org
