### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Daelon02** [AcalaNetwork/Acala#978]
Hi, we have this errors, when trying build project
[logs.txt](https://github.com/AcalaNetwork/Acala/files/6423575/logs.txt)

**Comment by xlc** [comment]
did you made any changes? looks like you are somehow using substrate master, which isn't supported.

**Comment by Daelon02** [comment]
> did you made any changes? looks like you are somehow using substrate master, which isn't supported.

Thats strange, we don't change anything, you think, need change rust version?

**Comment by xlc** [comment]
You can see our CI is passing and this is the setup https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/test.yml
